# frozen-string-literal: true

module Bioshogi
  module Analysis
    class DefenseInfo
      include ApplicationMemoryRecord
      memory_record do
        [
          ################################################################################ あとから追加する

          { key: "居玉",               parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: nil,  kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },

          ################################################################################ 矢倉

          { key: "いちご囲い",         parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "カニ囲い",           parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "カタ囲い",           parent: "カニ囲い",           related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "カブト囲い",         parent: nil,                  related_ancestors: ["いちご囲い", "カニ囲い"], alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "銀矢倉",             parent: "カニ囲い",           related_ancestors: ["カブト囲い"],             alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "金矢倉",             parent: "カニ囲い",           related_ancestors: ["カブト囲い", "大盾囲い"], alternate_name: nil, alias_names: "矢倉囲い",                                       turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "総矢倉",             parent: "金矢倉",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "菱矢倉",             parent: "総矢倉",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "富士見矢倉",         parent: "総矢倉",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "銀立ち矢倉",         parent: "金矢倉",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "高矢倉",             parent: "金矢倉",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "四角矢倉",           parent: "銀矢倉",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "角矢倉",             parent: "カニ囲い",           related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "豆腐矢倉",           parent: "金矢倉",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "隅矢倉",             parent: "金矢倉",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "流れ矢倉",           parent: "カニ囲い",           related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "金門矢倉",           parent: "カニ囲い",           related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "へこみ矢倉",         parent: "金門矢倉",           related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: "角換わりで表われやすいので角を持っていてもよい",                           },
          { key: "一文字矢倉",         parent: "カニ囲い",           related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "カギ囲い",           parent: "カニ囲い",           related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "オールド雁木",       parent: "カニ囲い",           related_ancestors: nil,                        alternate_name: nil, alias_names: "雁木囲い",                                       turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          # { key: "▲7七金型雁木",    parent: "オールド雁木",       related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "ツノ銀雁木",         parent: "カニ囲い",           related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "新型雁木",           parent: "ツノ銀雁木",         related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },

          { key: "菊水矢倉",           parent: "カニ囲い",           related_ancestors: nil,                        alternate_name: nil, alias_names: "しゃがみ矢倉",                                   turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: "カニ囲い→入城しない矢倉→菊水の変化もあるため親にカニ囲いを含めている",   },
          { key: "流線矢倉",           parent: "菊水矢倉",           related_ancestors: "流れ矢倉",                 alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: "判定が難しいのと、ほとんどケースで流線矢倉を菊水矢倉と呼んでいる",         },

          { key: "悪形矢倉",           parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "矢倉早囲い",         parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "天野矢倉",           parent: "矢倉早囲い",         related_ancestors: "大盾囲い",                 alternate_name: nil, alias_names: ["片矢倉", "藤井矢倉"],                           turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "土居矢倉",           parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: "角は持っていてもよい",                                                     },
          { key: "ムリヤリ矢倉",       parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: 16,  turn_eq: nil,  order_key: :order_second, not_have_pawn: nil, kill_only: nil, drop_only: false, pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: 0,                hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },

          { key: "カニ缶囲い",         parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "オリジナル雁木",     parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },

          ################################################################################ 舟囲い

          { key: "舟囲い",             parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "舟囲いDX",           parent: "舟囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "居飛車金無双",       parent: "舟囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "天守閣囲い",         parent: "舟囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: "▲７八金型天守閣囲い",                           turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "左美濃",             parent: "舟囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "角道不突き左美濃",   parent: "舟囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: "本来は対中飛車に対して用いるが、汎用的に使っている人もいるため限定しない", },
          { key: "居飛車金美濃",       parent: "舟囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "升田美濃",           parent: "舟囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "天守閣美濃",         parent: "左美濃",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "四枚美濃",           parent: "天守閣美濃",         related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "居飛車銀冠",         parent: "左美濃",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "居飛車金冠",         parent: "金矢倉",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "端玉銀冠",           parent: "天守閣美濃",         related_ancestors: "居飛車銀冠",               alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: "居飛車銀冠からの変化も一応ある",                                           },
          { key: "かんぴょう囲い",     parent: "居飛車銀冠",         related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "四枚銀冠",           parent: "居飛車銀冠",         related_ancestors: "四枚美濃",                 alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "串カツ囲い",         parent: "舟囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: ["早咲玉", "端美濃囲い"],                         turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },

          { key: "片穴熊",             parent: "舟囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: "穴熊", add_to_opponent: "対穴熊", technique_verify_info: nil, description: nil,                                                                        },
          { key: "居飛車穴熊",         parent: "片穴熊",             related_ancestors: nil,                        alternate_name: nil, alias_names: "イビ穴",                                         turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: "穴熊", add_to_opponent: "対穴熊", technique_verify_info: nil, description: nil,                                                                        },
          { key: "松尾流穴熊",         parent: "居飛車穴熊",         related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: "穴熊", add_to_opponent: "対穴熊", technique_verify_info: nil, description: nil,                                                                        },
          { key: "神吉流穴熊",         parent: "左美濃",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: "穴熊", add_to_opponent: "対穴熊", technique_verify_info: nil, description: nil,                                                                        },
          { key: "銀冠穴熊",           parent: "居飛車銀冠",         related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: "穴熊", add_to_opponent: "対穴熊", technique_verify_info: nil, description: nil,                                                                        },
          { key: "居飛穴音無しの構え", parent: "銀冠穴熊",           related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: "穴熊", add_to_opponent: "対穴熊", technique_verify_info: nil, description: nil,                                                                        },
          { key: "ビッグ4",            parent: "居飛穴音無しの構え", related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: "穴熊", add_to_opponent: "対穴熊", technique_verify_info: nil, description: nil,                                                                        },
          { key: "四枚穴熊",           parent: "居飛車穴熊",         related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: "穴熊", add_to_opponent: "対穴熊", technique_verify_info: nil, description: nil,                                                                        },
          { key: "矢倉穴熊",           parent: "金矢倉",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: "穴熊", add_to_opponent: "対穴熊", technique_verify_info: nil, description: nil,                                                                        },
          # { key: "角換わり穴熊",     parent: "金矢倉",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: "角", hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: "穴熊", add_to_opponent: "対穴熊", technique_verify_info: nil, description: nil,                                                                        },

          { key: "文鎮囲い",           parent: "舟囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "箱入り娘",           parent: "舟囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "金盾囲い",           parent: "舟囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "大盾囲い",           parent: "舟囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "ミレニアム囲い",     parent: "舟囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: ["トーチカ", "トーチカ囲い", "かまぼこ囲い", "かまくら囲い"],  turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                           },
          { key: "セメント囲い",       parent: "舟囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: ["カタツムリ", "トラック囲い"],                   turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "チョコレート囲い",   parent: "舟囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: ["屋根裏矢倉", "王冠"],                           turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "ボナンザ囲い",       parent: "舟囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },

          ################################################################################

          { key: "エルモ囲い",         parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: "elmo囲い",                                       turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "左山囲い",           parent: "エルモ囲い",         related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },

          ################################################################################ 居飛車のよくわからない囲いたち

          { key: "無責任矢倉",         parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "あずまや囲い",       parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "四段端玉",           parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "空中楼閣",           parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },

          ################################################################################ 中央

          { key: "中原囲い",           parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: "中原玉",                                         turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "中住まい",           parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "桐山流中原囲い",     parent: "中住まい",           related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "アヒル囲い",         parent: "中住まい",           related_ancestors: nil,                        alternate_name: nil, alias_names: ["金開き", "大阪囲い"],                           turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "裏アヒル囲い",       parent: "中住まい",           related_ancestors: nil,                        alternate_name: nil, alias_names: "不死鳥囲い",                                     turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "無敵囲い",           parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: "初心者囲い",                                     turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },

          ################################################################################

          { key: "早囲い",             parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: ["壁囲い", "早美濃"],                             turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: "早囲いと三手囲いは被っているためわかりにくい",                             },
          { key: "振り飛車エルモ",     parent: "早囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "ずれ美濃",           parent: "早囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: "簡易囲い",                                       turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "大隅囲い",           parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: ["大住囲い", "三手囲い", "金立囲い", "金立美濃"], turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: "大住囲いは考案者が広めようとしているところ",                               }, # https://note.com/agility40/n/nd149bdbc5849 https://ja.wikipedia.org/wiki/%E5%A4%A7%E4%BD%8F%E5%9B%B2%E3%81%84
          { key: "連盟美濃",           parent: "大隅囲い",           related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },

          ################################################################################

          { key: "片美濃囲い",         parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "美濃囲い",           parent: "片美濃囲い",         related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "ちょんまげ美濃",     parent: nil,                  related_ancestors: "美濃囲い",                 alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: "本当は陽動振り飛車からの流れなので後から26歩はちょっと違う",               },
          { key: "高美濃囲い",         parent: "美濃囲い",           related_ancestors: "ちょんまげ美濃",           alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "片銀冠",             parent: "片美濃囲い",         related_ancestors: "ちょんまげ美濃",           alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "銀冠",               parent: "片銀冠",             related_ancestors: "高美濃囲い",               alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "銀美濃",             parent: "片美濃囲い",         related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: "銀を打って作る場合もある",                                                 },
          { key: "金美濃",             parent: "早囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "振り飛車四枚美濃",   parent: "高美濃囲い",         related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "ダイヤモンド美濃",   parent: "美濃囲い",           related_ancestors: "銀美濃",                   alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "木村美濃",           parent: "片美濃囲い",         related_ancestors: "早囲い",                   alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "大山美濃",           parent: "片美濃囲い",         related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "美濃熊囲い",         parent: "片美濃囲い",         related_ancestors: "美濃囲い",                 alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "裾固め",             parent: "木村美濃",           related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "右矢倉",             parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },

          { key: "振り飛車ミレニアム", parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: "振りミレ",                                       turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "振り飛車端玉銀冠",   parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "振り飛車串カツ囲い", parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: ["右端美濃囲い"],                                 turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "振り飛車天守閣美濃", parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },

          { key: "紙穴熊",             parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: "穴熊", add_to_opponent: "対穴熊", technique_verify_info: nil, description: nil,                                                                        },
          { key: "振り飛車穴熊",       parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: "振り穴",                                         turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: "穴熊", add_to_opponent: "対穴熊", technique_verify_info: nil, description: nil,                                                                        },
          { key: "振り飛車銀冠穴熊",   parent: "振り飛車穴熊",       related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: "穴熊", add_to_opponent: "対穴熊", technique_verify_info: nil, description: nil,                                                                        },
          { key: "振り飛車ビッグ4",    parent: "振り飛車銀冠穴熊",   related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: "穴熊", add_to_opponent: "対穴熊", technique_verify_info: nil, description: nil,                                                                        },

          { key: "金無双",             parent: "大隅囲い",           related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "離れ金無双",         parent: "大隅囲い",           related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },

          { key: "坊主美濃",           parent: "ちょんまげ美濃",     related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "カブト美濃",         parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: true,  pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "振り飛車", group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },

          { key: "片ツノ銀囲い",       parent: "舟囲い",             related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil, add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                           },
          { key: "ツノ銀囲い",         parent: "片ツノ銀囲い",       related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil, add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                           },

          { key: "いかだ囲い",         parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: 0,                hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                          },
          { key: "雲隠れ玉",           parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: nil,  outbreak_skip: true, kill_count_lteq: 0,                hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "モノレール囲い",     parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },

          { key: "銀多伝",             parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
          { key: "金多伝",             parent: nil,                  related_ancestors: nil,                        alternate_name: nil, alias_names: nil,                                              turn_limit: nil, turn_eq: nil,  order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: false,   pawn_bishop_have_ok: nil,   pawn_have_ok: true, outbreak_skip: true, kill_count_lteq: nil,              hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil, sect_key: "居飛車",   group_key: nil,    add_to_self: nil, add_to_opponent: nil, technique_verify_info: nil, description: nil,                                                                        },
        ]
      end

      class_attribute :human_name, default: "囲い"

      include ShapeInfoRelation
      include TechAccessor
      include StyleAccessor

      # outbreak_skip で代用するため pawn_bishop_have_ok は無効化する
      def pawn_bishop_have_ok
        nil
      end
    end
  end
end
