# frozen-string-literal: true

# 判定は kill_count_lteq, pawn_bishop_have_ok: nil, :pawn_have_ok しか使ってない

module Bioshogi
  module Analysis
    class TechniqueInfo
      GYOKUHI_SEKKIN_TRIGGERS = [
        { piece_key: :rook, promoted: false, motion: :move },
        { piece_key: :king, promoted: false, motion: :move },
      ]

      include ApplicationMemoryRecord
      memory_record [
        { key: "たたきの歩",   group_key: nil, trigger_piece_key: { piece_key: :pawn,   promoted: false, motion: :drop }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "継ぎ歩",       group_key: nil, trigger_piece_key: { piece_key: :pawn,   promoted: false, motion: :drop }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "連打の歩",     group_key: nil, trigger_piece_key: { piece_key: :pawn,   promoted: false, motion: :drop }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "垂れ歩",       group_key: nil, trigger_piece_key: { piece_key: :pawn,   promoted: false, motion: :drop }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "金底の歩",     group_key: nil, trigger_piece_key: { piece_key: :pawn,   promoted: false, motion: :drop }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "蓋歩",         group_key: nil, trigger_piece_key: { piece_key: :pawn,   promoted: false, motion: :drop }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "こびん攻め",   group_key: nil, trigger_piece_key: { piece_key: :pawn,   promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "一間竜",       group_key: nil, trigger_piece_key: { piece_key: :rook,   promoted: true,  motion: :move }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "自陣飛車",     group_key: nil, trigger_piece_key: { piece_key: :rook,   promoted: false, motion: :drop }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "自陣角",       group_key: nil, trigger_piece_key: { piece_key: :bishop, promoted: false, motion: :drop }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "位の確保",     group_key: nil, trigger_piece_key: { piece_key: :silver, promoted: false, motion: :move }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: true, kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "浮き飛車",     group_key: nil, trigger_piece_key: { piece_key: :rook,   promoted: false, motion: :move }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: true, kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "玉飛接近",     group_key: nil, trigger_piece_key: GYOKUHI_SEKKIN_TRIGGERS,                                parent: nil,                                                                                      related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "守りの馬",     group_key: nil, trigger_piece_key: { piece_key: :bishop, promoted: true, motion: :move },  parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "双玉接近",     group_key: nil, trigger_piece_key: { piece_key: :king,   promoted: false, motion: :move }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: "双玉接近",     technique_detector: nil, description: nil,   },
        { key: "端玉",         group_key: nil, trigger_piece_key: { piece_key: :king,   promoted: false, motion: :move }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "中段玉",       group_key: nil, trigger_piece_key: { piece_key: :king,   promoted: false, motion: :move }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },

        { key: "腹銀",         group_key: nil, trigger_piece_key: { piece_key: :silver, promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "尻銀",         group_key: nil, trigger_piece_key: { piece_key: :silver, promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "肩銀",         group_key: nil, trigger_piece_key: { piece_key: :silver, promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "裾銀",         group_key: nil, trigger_piece_key: { piece_key: :silver, promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "頭銀",         group_key: nil, trigger_piece_key: { piece_key: :silver, promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },

        { key: "腹金",         group_key: nil, trigger_piece_key: { piece_key: :gold,   promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "尻金",         group_key: nil, trigger_piece_key: { piece_key: :gold,   promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "肩金",         group_key: nil, trigger_piece_key: { piece_key: :gold,   promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "裾金",         group_key: nil, trigger_piece_key: { piece_key: :gold,   promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "頭金",         group_key: nil, trigger_piece_key: { piece_key: :gold,   promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },

        { key: "割り打ちの銀", group_key: nil, trigger_piece_key: { piece_key: :silver, promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "たすきの銀",   group_key: nil, trigger_piece_key: { piece_key: :silver, promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "たすきの角",   group_key: nil, trigger_piece_key: { piece_key: :bishop, promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },

        { key: "壁金",         group_key: nil, trigger_piece_key: { piece_key: :gold,   promoted: false, motion: :move }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "壁銀",         group_key: nil, trigger_piece_key: { piece_key: :silver, promoted: false, motion: :move }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },

        { key: "銀不成",       group_key: nil, trigger_piece_key: { piece_key: :silver, promoted: false, motion: :move }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil, pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil, kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },

        { key: "桂頭の銀",     group_key: nil, trigger_piece_key: { piece_key: :silver, promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "桂頭の玉",     group_key: nil, trigger_piece_key: { piece_key: :king,   promoted: false, motion: :move }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "歩頭の桂",     group_key: nil, trigger_piece_key: { piece_key: :knight, promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "金頭の桂",     group_key: nil, trigger_piece_key: { piece_key: :knight, promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "田楽刺し",     group_key: nil, trigger_piece_key: { piece_key: :lance,  promoted: false, motion: :drop }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "下段の香",     group_key: nil, trigger_piece_key: { piece_key: :lance,  promoted: false, motion: :drop }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "歩の裏の香",   group_key: nil, trigger_piece_key: { piece_key: :lance,  promoted: false, motion: :drop }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "歩の裏の歩",   group_key: nil, trigger_piece_key: { piece_key: :pawn,   promoted: false, motion: :drop }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "マムシのと金", group_key: nil, trigger_piece_key: { piece_key: :pawn,   promoted: true,  motion: :move }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "継ぎ桂",       group_key: nil, trigger_piece_key: { piece_key: :knight, promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "跳ね違いの桂", group_key: nil, trigger_piece_key: { piece_key: :knight, promoted: :both, motion: :move }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "ふんどしの桂", group_key: nil, trigger_piece_key: { piece_key: :knight, promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "控えの桂",     group_key: nil, trigger_piece_key: { piece_key: :knight, promoted: false, motion: :drop }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "パンツを脱ぐ", group_key: nil, trigger_piece_key: { piece_key: :knight, promoted: false, motion: :move }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: 0,    hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "銀ばさみ",     group_key: nil, trigger_piece_key: { piece_key: :pawn,   promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: true, kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "端玉には端歩", group_key: nil, trigger_piece_key: { piece_key: :pawn,   promoted: false, motion: :move }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "居飛車の税金", group_key: nil, trigger_piece_key: nil,                                                    parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: true, kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "勝ち確5三と",  group_key: nil, trigger_piece_key: nil,                                                    parent: nil, related_ancestors: nil,  alias_names: "5三のと金に負けなし", turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "銀冠の小部屋", group_key: nil, trigger_piece_key: nil,                                                    parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "幽霊角",       group_key: nil, trigger_piece_key: nil,                                                    parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "遠見の角",     group_key: nil, trigger_piece_key: { piece_key: :bishop, promoted: false, motion: :both }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "突き違いの歩", group_key: nil, trigger_piece_key: nil,                                                    parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: true, kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "土下座の歩",   group_key: nil, trigger_piece_key: { piece_key: :pawn,   promoted: false, motion: :drop }, parent: nil, related_ancestors: nil,  alias_names: nil, turn_limit: nil, turn_eq: nil, order_key: nil, not_have_pawn: nil, kill_only: nil, drop_only: nil,  pawn_bishop_have_ok: nil, pawn_have_ok: nil, outbreak_skip: nil,  kill_count_lteq: nil,  hold_piece_not_in: nil, hold_piece_in: nil, hold_piece_empty: nil, hold_piece_eq: nil, op_hold_piece_eq: nil,     add_to_self: nil, add_to_opponent: nil,            technique_detector: nil, description: nil,   },
        { key: "2段ロケット",  group_key: nil, trigger_piece_key: nil,                                                    parent: nil, },
        { key: "3段ロケット",  group_key: nil, trigger_piece_key: nil,                                                    parent: "2段ロケット", },
        { key: "4段ロケット",  group_key: nil, trigger_piece_key: nil,                                                    parent: "3段ロケット", },
        { key: "5段ロケット",  group_key: nil, trigger_piece_key: nil,                                                    parent: "4段ロケット", },
        { key: "6段ロケット",  group_key: nil, trigger_piece_key: nil,                                                    parent: "5段ロケット", },
      ]

      class_attribute :human_name, default: "手筋"

      include ShapeInfoRelation
      include BasicAccessor
      include TreeMod
      include StaticKifMod
      include StyleAccessor

      class << self
        def rocket_list
          @rocket_list ||= values.find_all { |e| e.key.end_with?("ロケット") }
        end
      end
    end
  end
end
