require "../setup"
Analysis::FileNormalizer.new.call
# >>   [1 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/矢倉▲3七銀戦法.kif
# >>   [2 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/矢倉棒銀.kif
# >>   [3 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/ウソ矢倉.kif
# >>   [4 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/脇システム.kif
# >>   [5 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/森下システム.kif
# >>   [6 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/同型矢倉.kif
# >>   [7 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/雀刺し.kif
# >>   [8 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/米長流急戦矢倉.kif
# >>   [9 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/中原流急戦矢倉.kif
# >>   [10 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/阿久津流急戦矢倉.kif
# >>   [11 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/藤森流急戦矢倉.kif
# >>   [12 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/屋敷流二枚銀.kif
# >>   [13 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/屋敷流二枚銀棒銀型.kif
# >>   [14 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/矢倉中飛車.kif
# >>   [15 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/原始棒銀.kif
# >>   [16 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/四手角.kif
# >>   [17 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/カニカニ銀.kif
# >>   [18 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/カニカニ金.kif
# >>   [19 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/角換わり.kif
# >>   [20 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/一手損角換わり.kif
# >>   [21 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/角換わり腰掛け銀旧型.kif
# >>   [22 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/角換わり腰掛け銀.kif
# >>   [23 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/角換わり棒銀.kif
# >>   [24 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/角換わり早繰り銀.kif
# >>   [25 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/筋違い角.kif
# >>   [26 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/相筋違い角.kif
# >>   [27 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/筋違い角蟻地獄戦法.kif
# >>   [28 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/ゴリ違い角.kif
# >>   [29 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/木村定跡.kif
# >>   [30 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/相掛かり.kif
# >>   [31 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/相掛かり棒銀.kif
# >>   [32 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/塚田スペシャル.kif
# >>   [33 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/中原流相掛かり.kif
# >>   [34 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/中原飛車.kif
# >>   [35 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/腰掛け銀.kif
# >>   [36 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/鎖鎌銀.kif
# >>   [37 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/中座飛車.kif
# >>   [38 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/UFO銀.kif
# >>   [39 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/△2三歩戦法.kif
# >>   [40 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/△4五角戦法.kif
# >>   [41 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/加藤流袖飛車.kif
# >>   [42 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/▲5七金戦法.kif
# >>   [43 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/超急戦.kif
# >>   [44 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/遠山流.kif
# >>   [45 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/横歩取り.kif
# >>   [46 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/相横歩取り.kif
# >>   [47 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/青野流.kif
# >>   [48 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/勇気流.kif
# >>   [49 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/竹部スペシャル.kif
# >>   [50 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/△3三角型空中戦法.kif
# >>   [51 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/△3三桂戦法.kif
# >>   [52 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/角交換振り飛車.kif
# >>   [53 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/原始中飛車.kif
# >>   [54 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/中飛車ミレニアム.kif
# >>   [55 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/先手中飛車.kif
# >>   [56 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/矢倉流中飛車.kif
# >>   [57 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/飛騨の中飛車合掌造り.kif
# >>   [58 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/ツノ銀中飛車.kif
# >>   [59 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/英ちゃん流中飛車.kif
# >>   [60 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/中飛車左穴熊.kif
# >>   [61 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/▲5五龍中飛車.kif
# >>   [62 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/ゴキゲン中飛車.kif
# >>   [63 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/5筋位取り中飛車.kif
# >>   [64 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/ヒラメ戦法.kif
# >>   [65 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/四間飛車.kif
# >>   [66 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/ノーマル四間飛車.kif
# >>   [67 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/四間飛車ミレニアム.kif
# >>   [68 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/角道オープン四間飛車.kif
# >>   [69 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/はく式四間飛車.kif
# >>   [70 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/耀龍四間飛車.kif
# >>   [71 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/藤井システム.kif
# >>   [72 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/室岡システム.kif
# >>   [73 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/立石流四間飛車.kif
# >>   [74 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/レグスペ.kif
# >>   [75 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/やばボーズ流.kif
# >>   [76 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/三間飛車.kif
# >>   [77 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/ノーマル三間飛車.kif
# >>   [78 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/三間飛車ミレニアム.kif
# >>   [79 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/△3三飛戦法.kif
# >>   [80 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/石田流.kif
# >>   [81 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/早石田.kif
# >>   [82 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/ムリヤリ早石田.kif
# >>   [83 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/升田式石田流.kif
# >>   [84 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/鬼殺し.kif
# >>   [85 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/2手目△3ニ飛戦法.kif
# >>   [86 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/コーヤン流三間飛車.kif
# >>   [87 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/真部流.kif
# >>   [88 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/初手▲7八飛戦法.kif
# >>   [89 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/楠本式石田流.kif
# >>   [90 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/新鬼殺し.kif
# >>   [91 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/3→4→3戦法.kif
# >>   [92 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/戸辺流4→3戦法.kif
# >>   [93 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/向かい飛車.kif
# >>   [94 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/逆棒銀.kif
# >>   [95 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/ダイレクト向かい飛車.kif
# >>   [96 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/モノレール向かい飛車.kif
# >>   [97 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/メリケン向かい飛車.kif
# >>   [98 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/阪田流向かい飛車.kif
# >>   [99 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/オザワシステム.kif
# >>   [100 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/鬼殺し向かい飛車.kif
# >>   [101 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/菜々河流△4四角.kif
# >>   [102 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/菜々河流向かい飛車.kif
# >>   [103 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/天彦流▲6六角.kif
# >>   [104 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/天彦流向かい飛車.kif
# >>   [105 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/陽動振り飛車.kif
# >>   [106 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/角頭歩戦法.kif
# >>   [107 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/玉頭銀.kif
# >>   [108 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/つくつくぼうし戦法.kif
# >>   [109 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/ひねり飛車.kif
# >>   [110 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/耀龍ひねり飛車.kif
# >>   [111 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/幻想四間飛車.kif
# >>   [112 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/タランチュラ戦法.kif
# >>   [113 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/間宮久夢流.kif
# >>   [114 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/ポンポン桂.kif
# >>   [115 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/新ポンポン桂.kif
# >>   [116 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/ショーダンオリジナル.kif
# >>   [117 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/ショーダンシステム.kif
# >>   [118 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/村田システム.kif
# >>   [119 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/新村田システム.kif
# >>   [120 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/玉頭位取り.kif
# >>   [121 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/6筋位取り.kif
# >>   [122 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/5筋位取り.kif
# >>   [123 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/銀雲雀.kif
# >>   [124 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/地下鉄飛車.kif
# >>   [125 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/飯島流引き角戦法.kif
# >>   [126 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/飯島流相掛かり引き角.kif
# >>   [127 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/丸山ワクチン.kif
# >>   [128 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/エルモ急戦.kif
# >>   [129 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/▲4六銀右急戦.kif
# >>   [130 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/▲4六銀左急戦.kif
# >>   [131 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/▲4五歩早仕掛け.kif
# >>   [132 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/へなちょこ急戦.kif
# >>   [133 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/山田定跡.kif
# >>   [134 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/鷺宮定跡.kif
# >>   [135 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/棒銀.kif
# >>   [136 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/速攻棒銀.kif
# >>   [137 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/暴銀.kif
# >>   [138 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/左美濃急戦.kif
# >>   [139 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/右四間飛車.kif
# >>   [140 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/右四間飛車急戦.kif
# >>   [141 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/右四間飛車左美濃.kif
# >>   [142 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/右四間飛車超急戦.kif
# >>   [143 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/鳥刺し.kif
# >>   [144 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/嬉野流.kif
# >>   [145 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/新嬉野流.kif
# >>   [146 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/棒金.kif
# >>   [147 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/棒玉.kif
# >>   [148 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/超速▲3七銀.kif
# >>   [149 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/対振り持久戦.kif
# >>   [150 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/金無双急戦.kif
# >>   [151 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/袖飛車.kif
# >>   [152 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/△7二飛亜急戦.kif
# >>   [153 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/一直線穴熊.kif
# >>   [154 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/穴角戦法.kif
# >>   [155 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/穴角向かい飛車.kif
# >>   [156 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/下町流三間飛車.kif
# >>   [157 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/神吉流三間飛車.kif
# >>   [158 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/新石田流.kif
# >>   [159 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/鈴木流早石田.kif
# >>   [160 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/久保流早石田.kif
# >>   [161 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/菅井流三間飛車.kif
# >>   [162 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/うっかり三間飛車.kif
# >>   [163 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/アヒル戦法.kif
# >>   [164 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/裏アヒル戦法.kif
# >>   [165 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/極限早繰り銀.kif
# >>   [166 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/ゴリラの右手.kif
# >>   [167 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/△3三金型早繰り銀.kif
# >>   [168 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/三間飛車藤井システム.kif
# >>   [169 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/トマホーク.kif
# >>   [170 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/羽生式袖飛車.kif
# >>   [171 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/初手▲3六歩戦法.kif
# >>   [172 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/2手目△7四歩戦法.kif
# >>   [173 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/2手目△6二銀戦法.kif
# >>   [174 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/4手目△3三角戦法.kif
# >>   [175 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/魔界四間飛車.kif
# >>   [176 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/目くらまし戦法.kif
# >>   [177 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/端棒銀.kif
# >>   [178 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/カメレオン戦法.kif
# >>   [179 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/xaby角戦法.kif
# >>   [180 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/金沢流.kif
# >>   [181 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/Uターン飛車.kif
# >>   [182 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/阪田流2手目△9四歩.kif
# >>   [183 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/5手爆弾.kif
# >>   [184 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/必笑ひっかけ戦法.kif
# >>   [185 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/初手▲7八銀戦法.kif
# >>   [186 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/2手目△3二銀システム.kif
# >>   [187 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/メイドシステム.kif
# >>   [188 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/一間飛車.kif
# >>   [189 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/一間飛車右穴熊.kif
# >>   [190 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/ネコ式タテ歩取り.kif
# >>   [191 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/桐山流タテ歩棒銀.kif
# >>   [192 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/きんとうん戦法.kif
# >>   [193 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/たこ金戦法.kif
# >>   [194 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/きｍきｍ金.kif
# >>   [195 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/ゴリゴリ金.kif
# >>   [196 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/右玉.kif
# >>   [197 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/矢倉右玉.kif
# >>   [198 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/糸谷流右玉.kif
# >>   [199 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/羽生流右玉.kif
# >>   [200 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/角換わり右玉.kif
# >>   [201 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/雁木右玉.kif
# >>   [202 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/リッチブリッジ.kif
# >>   [203 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/ツノ銀型右玉.kif
# >>   [204 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/三段右玉.kif
# >>   [205 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/清野流岐阜戦法.kif
# >>   [206 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/風車.kif
# >>   [207 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/新風車.kif
# >>   [208 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/九間飛車.kif
# >>   [209 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/九間飛車左穴熊.kif
# >>   [210 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/ノーガード戦法.kif
# >>   [211 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/花村流名古屋戦法.kif
# >>   [212 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/GAVA角.kif
# >>   [213 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/英春流かまいたち戦法.kif
# >>   [214 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/高田流左玉.kif
# >>   [215 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/英春流カメレオン.kif
# >>   [216 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/パックマン戦法.kif
# >>   [217 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/山崎流パックマン.kif
# >>   [218 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/新米長玉.kif
# >>   [219 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/稲庭戦法.kif
# >>   [220 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/都成流△3一金.kif
# >>   [221 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/森安流袖飛車穴熊.kif
# >>   [222 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/鬼六流どっかん飛車.kif
# >>   [223 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/戦法/力戦.kif
# >>   [224 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/居玉.kif
# >>   [225 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/いちご囲い.kif
# >>   [226 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/カニ囲い.kif
# >>   [227 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/カタ囲い.kif
# >>   [228 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/カブト囲い.kif
# >>   [229 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/銀矢倉.kif
# >>   [230 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/金矢倉.kif
# >>   [231 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/総矢倉.kif
# >>   [232 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/菱矢倉.kif
# >>   [233 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/富士見矢倉.kif
# >>   [234 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/銀立ち矢倉.kif
# >>   [235 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/高矢倉.kif
# >>   [236 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/四角矢倉.kif
# >>   [237 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/角矢倉.kif
# >>   [238 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/豆腐矢倉.kif
# >>   [239 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/隅矢倉.kif
# >>   [240 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/流れ矢倉.kif
# >>   [241 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/金門矢倉.kif
# >>   [242 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/へこみ矢倉.kif
# >>   [243 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/一文字矢倉.kif
# >>   [244 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/カギ囲い.kif
# >>   [245 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/オールド雁木.kif
# >>   [246 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/ツノ銀雁木.kif
# >>   [247 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/新型雁木.kif
# >>   [248 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/菊水矢倉.kif
# >>   [249 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/流線矢倉.kif
# >>   [250 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/悪形矢倉.kif
# >>   [251 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/矢倉早囲い.kif
# >>   [252 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/天野矢倉.kif
# >>   [253 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/土居矢倉.kif
# >>   [254 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/ムリヤリ矢倉.kif
# >>   [255 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/カニ缶囲い.kif
# >>   [256 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/オリジナル雁木.kif
# >>   [257 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/舟囲い.kif
# >>   [258 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/舟囲いDX.kif
# >>   [259 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/居飛車金無双.kif
# >>   [260 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/天守閣囲い.kif
# >>   [261 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/左美濃.kif
# >>   [262 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/角道不突き左美濃.kif
# >>   [263 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/居飛車金美濃.kif
# >>   [264 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/升田美濃.kif
# >>   [265 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/天守閣美濃.kif
# >>   [266 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/四枚美濃.kif
# >>   [267 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/居飛車銀冠.kif
# >>   [268 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/居飛車金冠.kif
# >>   [269 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/端玉銀冠.kif
# >>   [270 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/かんぴょう囲い.kif
# >>   [271 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/四枚銀冠.kif
# >>   [272 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/串カツ囲い.kif
# >>   [273 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/片穴熊.kif
# >>   [274 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/居飛車穴熊.kif
# >>   [275 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/松尾流穴熊.kif
# >>   [276 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/神吉流穴熊.kif
# >>   [277 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/銀冠穴熊.kif
# >>   [278 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/居飛穴音無しの構え.kif
# >>   [279 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/ビッグ4.kif
# >>   [280 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/四枚穴熊.kif
# >>   [281 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/矢倉穴熊.kif
# >>   [282 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/文鎮囲い.kif
# >>   [283 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/箱入り娘.kif
# >>   [284 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/金盾囲い.kif
# >>   [285 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/大盾囲い.kif
# >>   [286 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/ミレニアム囲い.kif
# >>   [287 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/セメント囲い.kif
# >>   [288 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/チョコレート囲い.kif
# >>   [289 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/ボナンザ囲い.kif
# >>   [290 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/エルモ囲い.kif
# >>   [291 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/左山囲い.kif
# >>   [292 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/無責任矢倉.kif
# >>   [293 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/あずまや囲い.kif
# >>   [294 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/四段端玉.kif
# >>   [295 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/空中楼閣.kif
# >>   [296 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/中原囲い.kif
# >>   [297 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/中住まい.kif
# >>   [298 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/桐山流中原囲い.kif
# >>   [299 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/アヒル囲い.kif
# >>   [300 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/裏アヒル囲い.kif
# >>   [301 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/無敵囲い.kif
# >>   [302 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/早囲い.kif
# >>   [303 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/振り飛車エルモ.kif
# >>   [304 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/ずれ美濃.kif
# >>   [305 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/大隅囲い.kif
# >>   [306 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/連盟美濃.kif
# >>   [307 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/片美濃囲い.kif
# >>   [308 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/美濃囲い.kif
# >>   [309 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/ちょんまげ美濃.kif
# >>   [310 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/高美濃囲い.kif
# >>   [311 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/片銀冠.kif
# >>   [312 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/銀冠.kif
# >>   [313 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/銀美濃.kif
# >>   [314 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/金美濃.kif
# >>   [315 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/振り飛車四枚美濃.kif
# >>   [316 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/ダイヤモンド美濃.kif
# >>   [317 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/木村美濃.kif
# >>   [318 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/大山美濃.kif
# >>   [319 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/美濃熊囲い.kif
# >>   [320 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/裾固め.kif
# >>   [321 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/右矢倉.kif
# >>   [322 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/振り飛車ミレニアム.kif
# >>   [323 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/振り飛車端玉銀冠.kif
# >>   [324 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/振り飛車串カツ囲い.kif
# >>   [325 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/振り飛車天守閣美濃.kif
# >>   [326 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/紙穴熊.kif
# >>   [327 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/振り飛車穴熊.kif
# >>   [328 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/振り飛車銀冠穴熊.kif
# >>   [329 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/振り飛車ビッグ4.kif
# >>   [330 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/金無双.kif
# >>   [331 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/離れ金無双.kif
# >>   [332 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/坊主美濃.kif
# >>   [333 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/カブト美濃.kif
# >>   [334 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/片ツノ銀囲い.kif
# >>   [335 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/ツノ銀囲い.kif
# >>   [336 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/いかだ囲い.kif
# >>   [337 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/雲隠れ玉.kif
# >>   [338 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/モノレール囲い.kif
# >>   [339 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/銀多伝.kif
# >>   [340 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/囲い/金多伝.kif
# >>   [341 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/継ぎ歩.kif
# >>   [342 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/連打の歩.kif
# >>   [343 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/垂れ歩.kif
# >>   [344 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/金底の歩.kif
# >>   [345 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/こびん攻め.kif
# >>   [346 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/一間竜.kif
# >>   [347 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/位の確保.kif
# >>   [348 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/腹銀.kif
# >>   [349 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/尻銀.kif
# >>   [350 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/割り打ちの銀.kif
# >>   [351 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/たすきの銀.kif
# >>   [352 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/たすきの角.kif
# >>   [353 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/桂頭の銀.kif
# >>   [354 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/歩頭の桂.kif
# >>   [355 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/田楽刺し.kif
# >>   [356 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/継ぎ桂.kif
# >>   [357 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/ふんどしの桂.kif
# >>   [358 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/パンツを脱ぐ.kif
# >>   [359 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/銀ばさみ.kif
# >>   [360 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/端玉には端歩.kif
# >>   [361 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/銀冠の小部屋.kif
# >>   [362 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/幽霊角.kif
# >> U [363 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/遠見の角.kif
# >>   [364 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/突き違いの歩.kif
# >>   [365 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/土下座の歩.kif
# >>   [366 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/2段ロケット.kif
# >>   [367 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/3段ロケット.kif
# >>   [368 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/4段ロケット.kif
# >>   [369 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/5段ロケット.kif
# >>   [370 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/手筋/6段ロケット.kif
# >>   [371 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/角交換型.kif
# >>   [372 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/手得角交換型.kif
# >>   [373 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/手損角交換型.kif
# >>   [374 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/矢倉旧24手組.kif
# >>   [375 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/矢倉新24手組.kif
# >>   [376 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/居飛車.kif
# >>   [377 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/振り飛車.kif
# >>   [378 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/相居飛車.kif
# >>   [379 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/相振り飛車.kif
# >>   [380 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/対居飛車.kif
# >>   [381 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/対振り飛車.kif
# >>   [382 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/対抗形.kif
# >>   [383 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/急戦.kif
# >>   [384 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/持久戦.kif
# >>   [385 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/短手数.kif
# >>   [386 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/長手数.kif
# >>   [387 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/角不成.kif
# >>   [388 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/飛車不成.kif
# >>   [389 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/入玉.kif
# >>   [390 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/相入玉.kif
# >>   [391 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/相居玉.kif
# >>   [392 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/穴熊.kif
# >>   [393 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/対穴熊.kif
# >>   [394 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/相穴熊.kif
# >>   [395 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/大駒全ブッチ.kif
# >>   [396 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/大駒コンプリート.kif
# >>   [397 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/背水の陣.kif
# >>   [398 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/駒柱.kif
# >>   [399 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/穴熊の姿焼き.kif
# >>   [400 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/名人に定跡なし.kif
# >>   [401 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/都詰め.kif
# >>   [402 / 402] /Users/ikeda/src/bioshogi/lib/bioshogi/analysis/備考/ロケット.kif
