* 将棋の棋譜相互変換、棋譜から戦術抽出、超弱いAIなどのライブラリ

#+html: <a href="https://travis-ci.org/akicho8/bioshogi"><img src="https://travis-ci.org/akicho8/bioshogi.svg?branch=master" /></a>
#+html: <a href="https://codeclimate.com/github/akicho8/bioshogi/maintainability"><img src="https://api.codeclimate.com/v1/badges/7a1b5fe273e0e2f55043/maintainability" /></a>

  [[file:http://tk2-221-20341.vs.sakura.ne.jp/shogi/cpu-versus][file:https://raw.github.com/akicho8/bioshogi/master/bioshogi.png]]
  [[http://tk2-221-20341.vs.sakura.ne.jp/shogi/cpu-versus][デモ]]

#+BEGIN_SRC ruby
mediator = Mediator.start
[
  "７六歩", "８四歩", "７八金", "３二金",
  "２六歩", "８五歩", "７七角", "３四歩",
  "８八銀", "７七角成",
].each{|input|
  mediator.execute(input)
}
puts mediator.board
pp mediator.to_kif_a
# >>   ９ ８ ７ ６ ５ ４ ３ ２ １
# >> +---------------------------+
# >> |v香v桂v銀v金v玉 ・v銀v桂v香|一
# >> | ・v飛 ・ ・ ・ ・v金 ・ ・|二
# >> |v歩 ・v歩v歩v歩v歩 ・v歩v歩|三
# >> | ・ ・ ・ ・ ・ ・v歩 ・ ・|四
# >> | ・v歩 ・ ・ ・ ・ ・ ・ ・|五
# >> | ・ ・ 歩 ・ ・ ・ ・ 歩 ・|六
# >> | 歩 歩v馬 歩 歩 歩 歩 ・ 歩|七
# >> | ・ 銀 金 ・ ・ ・ ・ 飛 ・|八
# >> | 香 桂 ・ ・ 玉 金 銀 桂 香|九
# >> +---------------------------+
# >> ["▲７六歩(77)",
# >>  "▽８四歩(83)",
# >>  "▲７八金(69)",
# >>  "▽３二金(41)",
# >>  "▲２六歩(27)",
# >>  "▽８五歩(84)",
# >>  "▲７七角(88)",
# >>  "▽３四歩(33)",
# >>  "▲８八銀(79)",
# >>  "▽７七角成(22)"]
#+END_SRC

** サンプルコード

*** 初期配置文字列のパース

#+BEGIN_SRC ruby
info = Soldier.from_str("７六と")
info[:place].name # => "７六"
info[:promoted]   # => true
info[:piece].name # => "歩"
#+END_SRC

*** AI同士の対局 (ルールを守った上でランダムに指してみる)

#+BEGIN_SRC ruby
mediator = Mediator.start
loop do
  hand = mediator.current_player.brain.normal_all_hands.sample
  mediator.execute(hand)
  captured_soldier = mediator.opponent_player.executor.captured_soldier
  if executor.captured_soldier && executor.captured_soldier.piece.key == :king
    break
  end
end

p mediator
# >> 78手目: ▽後手番
# >>   ９ ８ ７ ６ ５ ４ ３ ２ １
# >> +---------------------------+
# >> | 角v桂v銀 ・v金 ・ ・ ・v香|一
# >> |v香 ・ ・ ・ ・v銀 ・ ・ 歩|二
# >> |v歩v歩v飛v歩 圭 ・ ・ ・v桂|三
# >> | ・ ・v歩 ・v金 ・ ・v歩 ・|四
# >> | ・ ・ ・ ・ 角 歩 ・ 歩v歩|五
# >> | ・ ・ 歩 ・ ・v歩v歩 ・ ・|六
# >> | 歩 歩 ・ 歩 歩 ・ ・ ・ 銀|七
# >> | 香 ・ ・ 金 ・ 飛 金 ・ 香|八
# >> | ・ 銀 ・ 玉 ・ ・ ・ 桂 ・|九
# >> +---------------------------+
# >> ▲先手の持駒:歩 玉
# >> ▽後手の持駒:歩

puts mediator.to_ki2_a.group_by.with_index{|v, i|i / 8}.values.collect{|v|v.join(" ")}
# >> ▲３八金(39) ▽４六歩打 ▲１二歩打 ▽３六歩(35) ▲５三桂成(65)
# >> ▲４八玉 ▽５二金 ▲５六歩 ▽６二飛 ▲１六歩 ▽７二飛 ▲５九玉 ▽６二玉
# >> ▲２六歩 ▽４二金 ▲４八飛 ▽５四歩 ▲７八銀 ▽５一金 ▲７六歩 ▽５五歩
# >> ▲同歩 ▽３二金 ▲５八飛 ▽３四歩 ▲７七桂 ▽９二香 ▲１八飛 ▽４二金
# >> ▲６八金 ▽８二飛 ▲２八銀 ▽４四歩 ▲１五歩 ▽４三金 ▲１七銀 ▽２四歩
# >> ▲６五桂 ▽３三金 ▲９八香 ▽４二銀 ▲２八飛 ▽３一角 ▲２七飛 ▽５二玉
# >> ▲９九角 ▽４三金 ▲３九金 ▽４五歩 ▲８九銀 ▽１四歩 ▲５四歩 ▽１三桂
# >> ▲４六歩 ▽６二飛 ▲４五歩 ▽５四金 ▲５七歩打 ▽２二角 ▲１八香 ▽５三玉
# >> ▲２五歩 ▽７四歩 ▲６九玉 ▽５二飛 ▲２六飛 ▽４八歩打 ▲２八飛 ▽７二飛
# >> ▲４八飛 ▽５五角 ▲同角 ▽７三飛 ▲３六歩 ▽３五歩 ▲９一角打 ▽１五歩
# >> ▲３八金 ▽４六歩打 ▲１二歩打 ▽３六歩 ▲５三桂成
#+END_SRC

*** 第23期竜王戦七番勝負第6局の再生

    KIFファイルを読み込み

#+BEGIN_SRC ruby
info = Bioshogi::Parser.parse(Pathname("ryuou20101214.kif"))
pp info.header
# >> {"対局ID"=>"333",
# >>  "開始日時"=>"2010/12/14 9:00",
# >>  "終了日時"=>"2010/12/15 19:13",
# >>  "表題"=>"竜王戦",
# >>  "棋戦"=>"第23期竜王戦七番勝負第6局",
# >>  "持ち時間"=>"各8時間",
# >>  "消費時間"=>"146▲479△471",
# >>  "場所"=>"岐阜・ホテルアソシア高山リゾート",
# >>  "手合割"=>"平手",
# >>  "先手"=>"羽生善治",
# >>  "後手"=>"渡辺　明"}
#+END_SRC

    棋譜を入力していく

#+BEGIN_SRC ruby
mediator = Mediator.start
info.move_infos.each{|info|
  mediator.execute(info[:input])
}
#+END_SRC

    最終形

#+BEGIN_SRC ruby
puts mediator.inspect
# >> 147:▲先手番
# >>   ９ ８ ７ ６ ５ ４ ３ ２ １
# >> +---------------------------+
# >> | ・v桂 ・ ・ 馬 ・ ・v桂v香|一
# >> |v飛 ・ ・ ・ ・ と ・ ・ ・|二
# >> | ・ ・ ・ 全v歩 ・v玉 ・ ・|三
# >> | ・ ・ ・ ・ ・ ・v桂 ・v金|四
# >> | ・v歩 ・ ・ ・ 銀v歩v歩v歩|五
# >> |v歩 ・ 歩v角 ・ ・ ・ ・ ・|六
# >> | ・ 歩 銀v歩vと ・ ・ ・ ・|七
# >> | 歩 ・ 玉 香 ・ ・ ・ ・ 香|八
# >> | 香 桂 ・ ・ ・ ・ 飛 ・ ・|九
# >> +---------------------------+
# >> blackの持駒:歩三金
# >> whiteの持駒:金二歩三銀
#+END_SRC

    KIF形式の棋譜確認

#+BEGIN_SRC ruby
puts mediator.to_kif_a.group_by.with_index{|v, i|i / 8}.values.collect{|v|v.join(" ")}
# >> ▲７六歩(77) ▽８四歩(83) ▲７八金(69) ▽３二金(41) ▲２六歩(27) ▽８五歩(84) ▲７七角(88) ▽３四歩(33)
# >> ▲８八銀(79) ▽７七角成(22) ▲７七銀(88) ▽４二銀(31) ▲３八銀(39) ▽７二銀(71) ▲９六歩(97) ▽９四歩(93)
# >> ▲４六歩(47) ▽６四歩(63) ▲４七銀(38) ▽６三銀(72) ▲６八玉(59) ▽３三銀(42) ▲５八金(49) ▽５四銀(63)
# >> ▲３六歩(37) ▽４二玉(51) ▲７九玉(68) ▽６五歩(64) ▲５六銀(47) ▽５二金(61) ▲１六歩(17) ▽１四歩(13)
# >> ▲３七桂(29) ▽３一玉(42) ▲４七金(58) ▽４四歩(43) ▲２五歩(26) ▽４三金(52) ▲８八玉(79) ▽２二玉(31)
# >> ▲４八金(47) ▽４二金(43) ▲２九飛(28) ▽４三金(42) ▲１八香(19) ▽９二香(91) ▲２八飛(29) ▽４二金(43)
# >> ▲２六飛(28) ▽５二金(42) ▲２九飛(26) ▽４三金(52) ▲２八飛(29) ▽４二金(43) ▲２七飛(28) ▽５二金(42)
# >> ▲４五歩(46) ▽４三金(52) ▲４四歩(45) ▽４四金(43) ▲２九飛(27) ▽４三金(44) ▲４六角打 ▽９三香(92)
# >> ▲４五歩打 ▽４二金(43) ▲４七銀(56) ▽９二飛(82) ▲３五歩(36) ▽３五歩(34) ▲３五角(46) ▽６四角打
# >> ▲５六歩(57) ▽９五歩(94) ▲９五歩(96) ▽９六歩打 ▲５七角(35) ▽９五香(93) ▲９八歩打 ▽３四歩打
# >> ▲３六銀(47) ▽７四歩(73) ▲１五歩(16) ▽１五歩(14) ▲２四歩(25) ▽２四銀(33) ▲２五銀(36) ▽４六歩打
# >> ▲２四銀(25) ▽２四歩(23) ▲８三銀打 ▽５二飛(92) ▲７四銀成(83) ▽９一角(64) ▲２四飛(29) ▽２三金(32)
# >> ▲２六飛(24) ▽２五歩打 ▲２五桂(37) ▽２四歩打 ▲１二歩打 ▽１二玉(22) ▲８四角(57) ▽４七歩成(46)
# >> ▲４七金(48) ▽１四金(23) ▲９五角(84) ▽２五歩(24) ▲３六飛(26) ▽２三玉(12) ▲５五歩(56) ▽４五銀(54)
# >> ▲３九飛(36) ▽４六歩打 ▲３六金(47) ▽３六銀(45) ▲３六飛(39) ▽４七歩成(46) ▲６三全(74) ▽９二飛(52)
# >> ▲５一角成(95) ▽６九銀打 ▲４五銀打 ▽２二桂打 ▲４三歩打 ▽３三金(42) ▲３五歩打 ▽３五歩(34)
# >> ▲３九飛(36) ▽７八銀成(69) ▲７八玉(88) ▽５五角(91) ▲３四歩打 ▽３四桂(22) ▲４二歩成(43) ▽５七と(47)
# >> ▲６九香打 ▽６六歩(65) ▲６六歩(67) ▽６八歩打 ▲６八香(69) ▽６七歩打 ▲４四銀打 ▽６六角(55)
# >> ▲３三銀成(44) ▽３三玉(23)
#+END_SRC

    KI2形式の棋譜確認

#+BEGIN_SRC ruby
puts mediator.to_ki2_a.group_by.with_index{|v, i|i / 8}.values.collect{|v|v.join(" ")}
# >> ▲７六歩 ▽８四歩 ▲７八金 ▽３二金 ▲２六歩 ▽８五歩 ▲７七角 ▽３四歩
# >> ▲８八銀 ▽７七角成 ▲同銀 ▽４二銀 ▲３八銀 ▽７二銀 ▲９六歩 ▽９四歩
# >> ▲４六歩 ▽６四歩 ▲４七銀 ▽６三銀 ▲６八玉 ▽３三銀 ▲５八金 ▽５四銀
# >> ▲３六歩 ▽４二玉 ▲７九玉 ▽６五歩 ▲５六銀 ▽５二金 ▲１六歩 ▽１四歩
# >> ▲３七桂 ▽３一玉 ▲４七金 ▽４四歩 ▲２五歩 ▽４三金 ▲８八玉 ▽２二玉
# >> ▲４八金 ▽４二金 ▲２九飛 ▽４三金 ▲１八香 ▽９二香 ▲２八飛 ▽４二金
# >> ▲２六飛 ▽５二金 ▲２九飛 ▽４三金 ▲２八飛 ▽４二金 ▲２七飛 ▽５二金
# >> ▲４五歩 ▽４三金 ▲４四歩 ▽同金 ▲２九飛 ▽４三金 ▲４六角打 ▽９三香
# >> ▲４五歩打 ▽４二金 ▲４七銀 ▽９二飛 ▲３五歩 ▽同歩 ▲同角 ▽６四角打
# >> ▲５六歩 ▽９五歩 ▲同歩 ▽９六歩打 ▲５七角 ▽９五香 ▲９八歩打 ▽３四歩打
# >> ▲３六銀 ▽７四歩 ▲１五歩 ▽同歩 ▲２四歩 ▽同銀 ▲２五銀 ▽４六歩打
# >> ▲２四銀 ▽同歩 ▲８三銀打 ▽５二飛 ▲７四銀成 ▽９一角 ▲２四飛 ▽２三金
# >> ▲２六飛 ▽２五歩打 ▲同桂 ▽２四歩打 ▲１二歩打 ▽同玉 ▲８四角 ▽４七歩成
# >> ▲同金 ▽１四金 ▲９五角 ▽２五歩 ▲３六飛 ▽２三玉 ▲５五歩 ▽４五銀
# >> ▲３九飛 ▽４六歩打 ▲３六金 ▽同銀 ▲同飛 ▽４七歩成 ▲６三全 ▽９二飛
# >> ▲５一角成 ▽６九銀打 ▲４五銀打 ▽２二桂打 ▲４三歩打 ▽３三金 ▲３五歩打 ▽同歩
# >> ▲３九飛 ▽７八銀成 ▲同玉 ▽５五角 ▲３四歩打 ▽同桂 ▲４二歩成 ▽５七と
# >> ▲６九香打 ▽６六歩 ▲同歩 ▽６八歩打 ▲同香 ▽６七歩打 ▲４四銀打 ▽６六角
# >> ▲３三銀成 ▽同玉
#+END_SRC

*** 駒が動ける場所

#+BEGIN_SRC ruby
mediator = Mediator.start
player = mediator.player_at(:black)
player.soldier_create("５五馬")
player.soldiers.first.move_list.each{|place|
  player.soldier_create("#{place}馬")
}
puts mediator.board
# >>   ９ ８ ７ ６ ５ ４ ３ ２ １
# >> +---------------------------+
# >> | 馬 ・ ・ ・ ・ ・ ・ ・ 馬|一
# >> | ・ 馬 ・ ・ ・ ・ ・ 馬 ・|二
# >> | ・ ・ 馬 ・ ・ ・ 馬 ・ ・|三
# >> | ・ ・ ・ 馬 馬 馬 ・ ・ ・|四
# >> | ・ ・ ・ 馬 馬 馬 ・ ・ ・|五
# >> | ・ ・ ・ 馬 馬 馬 ・ ・ ・|六
# >> | ・ ・ 馬 ・ ・ ・ 馬 ・ ・|七
# >> | ・ 馬 ・ ・ ・ ・ ・ 馬 ・|八
# >> | 馬 ・ ・ ・ ・ ・ ・ ・ 馬|九
# >> +---------------------------+
#+END_SRC

*** 座標のパース

    Placeクラス経由で扱えばだいたいパース可

#+BEGIN_SRC ruby
Place["４三"].name   # => "４三"
Place["４三"].name  # => "４三"
Place["43"].name    # => "４三"
#+END_SRC

    内部では別の座標

#+BEGIN_SRC ruby
Place["４三"].to_xy  # => [5, 2]
#+END_SRC

    引数が配列だったときのみスルー

#+BEGIN_SRC ruby
Place[[5, 2]].to_xy # => [5, 2]
#+END_SRC

*** 駒の情報取得例

#+BEGIN_SRC ruby
pp Piece["飛"].to_h
# >> {name: "飛",
# >>  promoted_name: "龍",
# >>  basic_names: ["飛", "rook"],
# >>  promoted_names: ["龍", "ROOK", "竜"],
# >>  names: ["飛", "rook", "龍", "ROOK", "竜"],
# >>  key: :rook,
# >>  :promotable=>true,
# >>  basic_once_vectors: [],
# >>  basic_repeat_vectors: [nil, [0, -1], nil, [-1, 0], [1, 0], nil, [0, 1], nil],
# >>  promoted_once_vectors: # >>   [[-1, -1], [0, -1], [1, -1], [-1, 0], nil, [1, 0], [-1, 1], [0, 1], [1, 1]],
# >>  promoted_repeat_vectors: [nil, [0, -1], nil, [-1, 0], [1, 0], nil, [0, 1], nil]}
#+END_SRC

*** 盤面テキストのパース

#+BEGIN_SRC ruby
board = <<-EOT
+---------------------------+
| ・v桂 ・ ・ 馬 ・ ・v桂v香|
|v飛 ・ ・ ・ ・ と ・ ・ ・|
| ・ ・ ・ 全v歩 ・v玉 ・ ・|
| ・ ・ ・ ・ ・ ・v桂 ・v金|
| ・v歩 ・ ・ ・ 銀v歩v歩v歩|
|v歩 ・ 歩v角 ・ ・ ・ ・ ・|
| ・ 歩 銀v歩vと ・ ・ ・ ・|
| 歩 ・ 玉 香 ・ ・ ・ ・ 香|
| 香 桂 ・ ・ ・ ・ 飛 ・ ・|
+---------------------------+
EOT
BoardParser.parse(board)
# => {
  white: {
    "８一桂", "２一桂", "１一香", "９二飛", "５三歩", "３三玉", "３四桂", "１四金",
    "８五歩", "３五歩", "２五歩", "１五歩", "９六歩", "６六角", "６七歩", "５七と",
  },
  black: {
    "５一馬", "４二と", "６三全", "４五銀", "７六歩", "８七歩", "７七銀", "９八歩",
    "７八玉", "６八香", "１八香", "９九香", "８九桂", "３九飛",
  },
}
#+END_SRC

*** KIF形式の盤面表示と盤面の駒の確認

#+BEGIN_SRC ruby
mediator = Mediator.start
mediator.piece_plot
puts mediator.board

mediator.board["５五"]      # => nil
mediator.board["８八"].name # => "▲８八角"
mediator.board["２八"].name # => "▲２八飛"
mediator.board["５九"].name # => "▲５九玉"
# >>   ９ ８ ７ ６ ５ ４ ３ ２ １
# >> +---------------------------+
# >> |v香v桂v銀v金v玉v金v銀v桂v香|一
# >> | ・v飛 ・ ・ ・ ・ ・v角 ・|二
# >> |v歩v歩v歩v歩v歩v歩v歩v歩v歩|三
# >> | ・ ・ ・ ・ ・ ・ ・ ・ ・|四
# >> | ・ ・ ・ ・ ・ ・ ・ ・ ・|五
# >> | ・ ・ ・ ・ ・ ・ ・ ・ ・|六
# >> | 歩 歩 歩 歩 歩 歩 歩 歩 歩|七
# >> | ・ 角 ・ ・ ・ ・ ・ 飛 ・|八
# >> | 香 桂 銀 金 玉 金 銀 桂 香|九
# >> +---------------------------+
#+END_SRC

*** ５五将棋の例

#+BEGIN_SRC ruby
Board.dimensiton_change([5, 5])
mediator = Mediator.start
soldiers = ["５五玉", "４五金", "３五銀", "２五角", "１五飛", "５四歩"]
mediator.players.each do |player|
  _soldiers = soldiers.collect{|s|
    s = Soldier.from_str(s)
    s.merge(place: s[:place].flip_if_white(player.location))
  }
  player.soldier_create(_soldiers)
end
mediator.piece_box_clear
p mediator
# >> 1手目: ▲先手番
# >>   ５ ４ ３ ２ １
# >> +---------------+
# >> |v飛v角v銀v金v玉|一
# >> | ・ ・ ・ ・v歩|二
# >> | ・ ・ ・ ・ ・|三
# >> | 歩 ・ ・ ・ ・|四
# >> | 玉 金 銀 角 飛|五
# >> +---------------+
# >> ▲先手の持駒:
# >> ▽後手の持駒:

mediator.execute("２四銀")
mediator.execute("４二銀")
mediator.execute("３四角")
mediator.execute("３二角")
mediator.execute("２三銀")
mediator.execute("４三銀")
mediator.execute("１二銀")
mediator.execute("同金")
mediator.execute("同角")
p mediator
# >> 10手目: ▽後手番
# >>   ５ ４ ３ ２ １
# >> +---------------+
# >> |v飛 ・ ・ ・v玉|一
# >> | ・ ・v角 ・ 角|二
# >> | ・v銀 ・ ・ ・|三
# >> | 歩 ・ ・ ・ ・|四
# >> | 玉 金 ・ ・ 飛|五
# >> +---------------+
# >> ▲先手の持駒:歩 金
# >> ▽後手の持駒:銀
#+END_SRC

*** NegaMax法のログの見方

    3x3の盤面で対角線上に歩がある場合の駆け引き

#+BEGIN_SRC ruby
Bioshogi.logger = ActiveSupport::Logger.new(STDOUT)
Board.dimensiton_change([3, 3]) do
  mediator = Mediator.new
  mediator.board.placement_from_human("▲３三歩 △１一歩")
  puts mediator
  pp NegaAlphaDiver.run(player: mediator.player_at(:black), depth_max: 1)
end
# >> 1手目: ▲先手番
# >>   ３ ２ １
# >> +---------+
# >> | ・ ・v歩|一
# >> | ・ ・ ・|二
# >> | 歩 ・ ・|三
# >> +---------+
# >> ▲先手の持駒:
# >> ▽後手の持駒:
# >>    0  試指 ▲３二歩(33) (1/2)
# >> 葉 1      試指 ▽１二歩(11) (1/2)
# >> 葉 1      評価 ▽１二歩(11)    +0
# >> 葉 1      試指 ▽１二歩成(11) (2/2)
# >> 葉 1      評価 ▽１二歩成(11) +1100
# >> 葉 1      確定 ▽１二歩成(11) +1100 候補:[▽１二歩成(11)(1100) ▽１二歩(11)(0)]
# >>    0  評価 ▲３二歩(33) -1100
# >>    0  試指 ▲３二歩成(33) (2/2)
# >> 葉 1      試指 ▽１二歩(11) (1/2)
# >> 葉 1      評価 ▽１二歩(11) -1100
# >> 葉 1      試指 ▽１二歩成(11) (2/2)
# >> 葉 1      評価 ▽１二歩成(11)    +0
# >> 葉 1      確定 ▽１二歩成(11)    +0 候補:[▽１二歩成(11)(0) ▽１二歩(11)(-1100)]
# >>    0  評価 ▲３二歩成(33)    +0
# >>    0  確定 ▲３二歩成(33)    +0 候補:[▲３二歩成(33)(0) ▲３二歩(33)(-1100)]
# >> {:hand=>"▲３二歩成(33)",
# >>  :score=>0,
# >>  :level=>0,
# >>  :reading_hands=>["▲３二歩成(33)", "▽１二歩成(11)"]}
#+END_SRC

- 自分(先手)には「３二歩」「３二歩成」の二通りの手があることがわかり、どっちにするか問題。
- それぞれ指したとき、後手側になってみていちばん良くなる手を探す。
- 自分にとってはそれは負なのでマイナスとする
- 「３二歩」のとき後手は「１二歩」「１二歩成」の二通りを考えていて「１二歩成」の方が良いとわかる。+1100点。
- 自分にとってはそれは負なので「▲３二歩」なら -1100 点。
- 同様に「▲３二歩成」なら 0 点。
- -1100 になる手と、0点になる手なら当然0点になる「▲３二歩成」を指した方がいいという結果になる

*** ミクロコスモスの棋譜を読む

#+BEGIN_SRC ruby
puts Parser.file_parse("microcosmos.kif").to_bod
# >> 後手の持駒：飛二 角 銀 桂二 香 歩三
# >>   ９ ８ ７ ６ ５ ４ ３ ２ １
# >> +---------------------------+
# >> | ・ ・ ・ と と と と 杏 ・|一
# >> | ・v金 ・ ・ ・ ・ ・ ・ ・|二
# >> | ・v桂 ・ ・v歩v歩v歩v歩 ・|三
# >> | ・ ・ とv銀v金vと ・ ・ ・|四
# >> |v馬v圭 香 ・ ・ ・ ・ 銀 ・|五
# >> | ・ 歩 歩 ・ ・ ・ と ・ 香|六
# >> | ・ ・ ・ ・ ・ ・ ・ ・ ・|七
# >> | ・ ・ ・ ・ とv銀 歩 ・ ・|八
# >> | ・ ・ ・ ・ ・ ・ 金 金v玉|九
# >> +---------------------------+
# >> 先手の持駒：なし
# >> 手数＝1525 ▲２九金打 まで
# >>
# >> 後手番
#+END_SRC

** 仕様

*** 棋譜サフィックス語の解釈

    | コマンド | 意味               | 詳細                                                                       |
    |----------+--------------------+----------------------------------------------------------------------------|
    | 右       | 右の方のを選択     | 移動元を指定座標より右で絞る(龍馬は例外で指定座標を無視し左右の方向)       |
    | 左       | 左の方のを選択     | 移動元を指定座標より左で絞る(龍馬は例外で指定座標を無視し左右の方向)       |
    | 上       | 下の方のを上げる   | 移動元を指定座標より下で絞る                                               |
    | 引       | 上の方のを引く     | 移動元を指定座標より上で絞る。下げるから "下" と書いてしまいがちなので注意 |
    | 寄       | 横一列の中から選択 | 移動元を指定座標のY座標で絞る                                              |
    | 直       | 縦一列の中から選択 | 移動元を指定座標のX座標で絞る                                              |

    もっと簡単に

#+BEGIN_EXAMPLE
    ↓引く

                   右の方にあるやつ

●    ← 寄せる

         ↑もち上げる
↑
直
#+END_EXAMPLE

*** 棋譜の表記

    | 表記       | 意味                     |
    |------------+--------------------------|
    | ７六歩(77) | ７七の歩を７六に移動     |
    | ７六歩     | ７六歩(77) の省略形      |
    | ２二角成   | ２二に角が移動して成った |
    | ５五飛打   | ５五に持駒の飛車を打った |
    | 同歩       | 1手前の座標に歩を移動    |

*** 主な例外

    | 例外                   | 意味                                           | どんなときに起きる？                                                                    |
    |------------------------+------------------------------------------------+-----------------------------------------------------------------------------------------|
    | BioshogiError            | すべての例外の親                               |                                                                                         |
    | MustNotHappen          | ありえない処理                                 | ブログラムがバグっている                                                                |
    | AmbiguousFormatError   | 指定座標に移動できる駒が多すぎる               | 初手 "▲５八金"                                                                         |
    | SyntaxDefact           | とりあえず表記が違う                           | 駒の配置時に "４二銀成" とした                                                          |
    | PieceNotFound          | 指定の名前の駒が存在しない                     | 龍のつもりで蛇と書いた                                                                  |
    | HoldPieceNotFound      | 持駒が無い                                     | 歩を持っていないのに歩を打とうとした                                                    |
    | PieceAlredyExist       | 自分の駒の上に自分の駒を初期配置               | 配置時に2連続で "９七歩"                                                                |
    | AlredyPromoted         | すでに成っている                               | "５五" の龍を "５一飛成"                                                                |
    | BeforePlaceNotFound    | 「同」に対する座標が不明                       | 初手 "同歩"                                                                             |
    | RuleError              | 反則系例外の親                                 | 二歩など                                                                                |
    | CommonError            | 黙認できる例外の親                             | いまのところ二歩と手番間違いの2つだけ                                                   |
    | SamePlaceDifferent     | 座標と「同」を同時に指定したが一致しない       | "同歩" だけでいいのに "２四同歩" と場所を明示したとき、その前の指し手が "２四○" でない |
    | FileFormatError        | ファイルのフォーマットがおかしい               | KIFファイルとして画像ファイルを読ませた                                                 |
    | KeyNotFound            | 手合割・囲い・戦型などのあるはずのデータがない | 手合割で「二枚落ち」と書くところを「飛車角落ち」と書いた                                |
    | BrainProcessingHeavy   | 処理が重すぎる                                 | 反復深化深さ優先探索でのタイムリミットが短かすぎて指し手を生成できない                  |

    反則系 (RuleError のサブクラス)

    こちらはプログラムの不具合や、棋譜の入力ミスに起因するものが多いので例外を出す

    | 例外                            | 意味                                               | どんなときに起きる？               |
    |---------------------------------+----------------------------------------------------+------------------------------------|
    | NoPromotablePiece               | "成" "不成" は指定できない                         | １三金不成、３三玉成               |
    | NotFoundOnBoard                 | 盤面に指定の駒がない                               | ２七に歩がないのに２六歩(27)とした |
    | CandidateSoldiersNotInclude     | 指定座標に移動できる駒に移動元の駒が含まれていない | 初手 "▲25歩(27)"                  |
    | DeadPieceRuleError              | 死に駒(行きどころのない駒)を作った                 | ▲１一桂                           |
    | PromotedPiecePutOnError         | 成った状態で打とうとした                           | ５五龍打                           |
    | PromotedPieceToNormalPiece      | 成駒を成ってない状態に戻そうとした                 | ５五龍を５六飛                     |
    | SamePlayerBattlerOverwrideError | 自分の駒の上に自分の駒を指した                     | 初手 "８八飛(28)"                  |
    | ReversePlayerPieceMoveError     | 相手の駒を動かそうとした                           | ▲の手番で初手 "３四歩"            |
    | MovableBattlerNotFound          | 指定座標に移動できる駒が一つもない                 | 平手で初手 "▲３四歩" や ▲22角成  |

    一部の例外を抑制できる系の反則

    これらは棋譜にでてくるので別扱いにする

    | 例外                     | 意味     | どんなときに起きる？     |
    |--------------------------+----------+--------------------------|
    | DoublePawnCommonError    | 二歩     | 歩がある縦列に歩を打った |
    | DifferentTurnCommonError | 手番違い | 平手で初手△３四歩       |

*** 表示座標系

    | 9    | 8 |    7 | 6 | 5 | 4 |    3 | 2 | 1    |    |
    |------+---+------+---+---+---+------+---+------+----|
    | ９一 |   |      |   |   |   |      |   | １一 | 一 |
    |      |   |      |   |   |   |      |   |      | 二 |
    |      |   |      |   |   |   | ３三 |   | １三 | 三 |
    |      |   |      |   |   |   |      |   |      | 四 |
    |      |   |      |   |   |   |      |   |      | 五 |
    |      |   |      |   |   |   |      |   |      | 六 |
    |      |   | ７七 |   |   |   |      |   |      | 七 |
    |      |   |      |   |   |   |      |   |      | 八 |
    | ９九 |   |      |   |   |   |      |   | １九 | 九 |

*** コード座標系

    |   | 0   | 1 |   2 | 3 | 4 | 5 |   6 | 7 | 8   |
    |---+-----+---+-----+---+---+---+-----+---+-----|
    | 0 | 0,0 |   |     |   |   |   |     |   | 8,0 |
    | 1 |     |   |     |   |   |   |     |   |     |
    | 2 |     |   |     |   |   |   | 6,2 |   | 8,2 |
    | 3 |     |   |     |   |   |   |     |   |     |
    | 4 |     |   |     |   |   |   |     |   |     |
    | 5 |     |   |     |   |   |   |     |   |     |
    | 6 |     |   | 2,6 |   |   |   |     |   |     |
    | 7 |     |   |     |   |   |   |     |   |     |
    | 8 | 0,8 |   |     |   |   |   |     |   | 8,8 |

*** 棋譜のパース

    - "７六歩" の場合 "７六" と "歩" に分離する
    - "２二角成" の場合 "２二" と "角" と "成" に分離する
    - 同銀の場合、同がどこを差しているのか、前の座標を見る
    - "５八金右" の場合、５八から見て右下にある金が斜め上に上がったという意味なのでこの解釈が難しい
    - "４八" に金があった場合、"５八金右" は真横の金なのか、斜め下の金なのか、どっちだろう
    - ネット上にある棋譜はだいたい "７六歩(77)" の形式になっていて７七にあったことを明示しているのでがんばって推測しなくてもいい

*** 棋譜ファイルの形式についての考察

**** KIFフォーマット

#+BEGIN_EXAMPLE
# ----  Kifu for Windows V6.22 棋譜ファイル  ----
開始日時：2000/01/01 00:00:00
終了日時：2000/01/01 01:00:00
棋戦：(棋戦)
持ち時間：(持ち時間)
手合割：平手　　
先手：(先手)
後手：(後手)
手数----指手---------消費時間--
*対局前コメント
   1 ７六歩(77)   ( 0:10/00:00:10)
*コメント1
   2 ３四歩(33)   ( 0:10/00:00:20)
   3 ６六歩(67)   ( 0:10/00:00:30)
   4 ８四歩(83)   ( 0:10/00:00:40)
*コメント2
   5 投了         ( 0:10/00:00:50)
まで4手で後手の勝ち
#+END_EXAMPLE

    - 移動元が明記されているためプログラム的に扱いやすい
    - 例えば "５八金右" は "５八金(49)" と表わすので「右」の方にある金を探さなくても済む
    - ヘッダーは KI2 と共通でよい
    - ヘッダーとコンテンツを分けるセパレーターは */^手数.*/* らしい。基本、これがあるかどうかで KIF or KIF2 の判別ができそう
    - コメントは *直前の指し手* に結び付いている
    - しかし対局前のコメントは *結び付く指し手がない* ため別データ扱いと考える方がよさそう
    - 「投了」は指し手とは別に管理した方がよい。指し手に「投了」が入ってくるとプログラムが複雑になるため
    - 「投了」の横の時間がある場合、それはどれだけ考えて投了したかを表す情報なので、見ないといけない。
    - 「投了」がないと将棋山脈ではKIFと見なされない。なお激指は「投了」を入れてくれない。
    - アスタリスクで始まるコメント部分には何を書いてもいいというのを利用して一手目の上に開始前メッセージがあるのがおかしい。結び付く手がない。開始前メッセージはヘッダーに入れる仕様だとよかった。
    - コメントには「#」と「*」の2つがあり、「#」はプログラム用のコメントで「*」は中継記者のコメント
    - 手合割の値の最後に謎の全角スペース2つあるのは謎。とくに気にしなくてもよいみたい
    - 棋譜部分の手数番号の前のインデントはなくてもよい
    - 激指(定跡道場4)は最後の指し手が「中断, 投了, 持将棋, 千日手, 詰み, 切れ負け」以外になっていると読み込めない。ここで何か判断しているようでもないので、この行は不要かもしれない。ただ投了までの時間を入れるにはこの行がいる。

**** KI2フォーマット

#+BEGIN_EXAMPLE
開始日時：2000/01/01 00:00
終了日時：2000/01/01 01:00
表題：(表題)
棋戦：(棋戦)
戦型：(戦型)
持ち時間：(持ち時間)
場所：(場所)
掲載：(掲載)
立会人：(立会人)
副立会人：(副立会人)
記録係：(記録係)
Web Page：(Web Page)
通算成績：(通算成績)
先手：(先手)
後手：(後手)

*対局前コメント
▲７六歩    △３四歩
*コメント1
▲６六歩△８四歩
*コメント2
まで4手で後手の勝ち
#+END_EXAMPLE

    - "５八金右" "同歩" など人が書いた風の棋譜になっている
    - ヘッダーとコンテンツを分けるセパレーターは *最初の空行*
    - 指し手は横に何個並んでもいいっぽい
    - 指し手のセパレータは *空白ではない* 。くっついている場合もあるので三角マークの前で区切る
    - なお *△* ではなく *▽* の場合もあるので *▲△▼▽* の4つに対応すること
    - *投了* がない
    - "#" もない(？)
    - *まで○手で○手の勝ち* は必要みたい

*** 英語表記対応表

    | 日本語   | 英語     |
    |----------+----------|
    | 歩       | pawn     |
    | 角       | bishop   |
    | 飛       | rook     |
    | 香       | lance    |
    | 桂       | knight   |
    | 銀       | silver   |
    | 金       | gold     |
    | 玉       | king     |
    | 成った   | promoted |
    | 盤面     | board    |
    | 座標     | place    |
    | 相対座標 | vector   |
    | 先手     | black    |
    | 後手     | white    |
    | 対局室   | mediator |

** コマンドラインツール

#+BEGIN_SRC shell
% bioshogi --help
Commands:
  bioshogi convert         # 棋譜フォーマット変換
  bioshogi help [COMMAND]  # Describe available commands or one specific command
  bioshogi input_parser    # 入力
  bioshogi piece           # 駒一覧
  bioshogi versus          # CPU同士の対戦

Options:
  [--debug], [--no-debug]
  [--quiet], [--no-quiet]
#+END_SRC

** 参考リンク集

   - 棋譜の形式について http://wiki.optus.nu/shogi/index.php?post=%B4%FD%C9%E8%A4%CE%B7%C1%BC%B0%A4%CB%A4%C4%A4%A4%A4%C6
   - 二歩 - Wikipedia http://ja.wikipedia.org/wiki/%E4%BA%8C%E6%AD%A9#cite_note-4
   - CC Resources for Shogi Applications | 将棋アプリ用クリエイティブコモンズ画像 http://mucho.girly.jp/bona/
   - 将棋所：USIプロトコルとは http://www.geocities.jp/shogidokoro/usi.html
   - CSA標準棋譜ファイル形式 http://www.computer-shogi.org/protocol/record_v22.html

** ライセンス

   - Ricty Diminished https://www.rs.tus.ac.jp/yyusa/ricty_diminished.html
