# frozen-string-literal: true

module Warabi
  class AttackInfo
    include ApplicationMemoryRecord
    memory_record [
      # 1
      {wars_code: "2000",      key: "３七銀戦法",           parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :sente, not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2001",      key: "脇システム",           parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :sente, not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2002",      key: "矢倉棒銀",             parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2003",      key: "森下システム",         parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :sente, not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2004",      key: "雀刺し",               parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2005",      key: "米長流急戦矢倉",       parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2006",      key: "カニカニ銀",           parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2007",      key: "中原流急戦矢倉",       parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2008",      key: "阿久津流急戦矢倉",     parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      # 2
      {wars_code: "2009",      key: "矢倉中飛車",           parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2010",      key: "右四間飛車",           parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2011",      key: "原始棒銀",             parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: true, kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2012",      key: "右玉",                 parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2013",      key: "かまいたち戦法",       parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2014",      key: "パックマン戦法",       parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: 2,   order_key: :gote,  not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2015",      key: "新米長玉",             parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: 2,    turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2016",      key: "稲庭戦法",             parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2017",      key: "四手角",               parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: true, cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      # 3
      {wars_code: "2019",      key: "一間飛車",             parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: true, cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2020",      key: "一間飛車穴熊",         parent: "一間飛車",         other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: true, cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2021",      key: "都成流",               parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :gote,  not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: "歩", },
      {wars_code: "2022",      key: "右四間飛車左美濃",     parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: true, cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2100",      key: "角換わり",             parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :sente, not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: "角", },
      {wars_code: "2101",      key: "角換わり腰掛け銀",     parent: "角換わり",         other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: "角", },
      {wars_code: "2102",      key: "角換わり棒銀",         parent: "角換わり",         other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: "角", },
      {wars_code: "2103",      key: "角換わり早繰り銀",     parent: "角換わり",         other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: "角", },
      {wars_code: "2104",      key: "筋違い角",             parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: true, not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: 0,   hold_piece_eq: nil,  },
      # 4
      {wars_code: "2105",      key: "木村定跡",             parent: "角換わり腰掛け銀", other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: "角", },
      {wars_code: "2106",      key: "一手損角換わり",       parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :gote,  not_have_pawn: nil,  kill_only: true, direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: "角", },
      {wars_code: "2200",      key: "相掛かり",             parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: 15,   turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: "歩", },
      {wars_code: "2201",      key: "相掛かり棒銀",         parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: "歩", },
      {wars_code: "2202",      key: "塚田スペシャル",       parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: true, not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2203",      key: "中原流相掛かり",       parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2204",      key: "中原飛車",             parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2205",      key: "腰掛け銀",             parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: "角", hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2206",      key: "鎖鎌銀",               parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: "角", hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      # 5
      {wars_code: "2207",      key: "８五飛車戦法",         parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2208",      key: "UFO銀",                parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: true, cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2300",      key: "横歩取り",             parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2301",      key: "△３三角型空中戦法",   parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :gote,  not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2302",      key: "△３三桂戦法",         parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :gote,  not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2303",      key: "△２三歩戦法",         parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :gote,  not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2304",      key: "△４五角戦法",         parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :gote,  not_have_pawn: nil,  kill_only: nil,  direct_only: true, not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2305",      key: "相横歩取り",           parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: "角", hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2400",      key: "ゴキゲン中飛車",       parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      # 6
      {wars_code: "2401",      key: "ツノ銀中飛車",         parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2402",      key: "平目",                 parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2403",      key: "風車",                 parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: nil,         key: "新風車",               parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2404",      key: "英ちゃん流中飛車",     parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2405",      key: "原始中飛車",           parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2406",      key: "加藤流袖飛車",         parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2407",      key: "５七金戦法",           parent: nil,                other_parents: nil, alias_names: ["４六金戦法", "金立ち戦法"], turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2408",      key: "超急戦",               parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2410",      key: "中飛車左穴熊",         parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      # 7
      {wars_code: "2411",      key: "遠山流",               parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: "角", hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2500",      key: "四間飛車",             parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2501",      key: "藤井システム",         parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2502",      key: "立石流",               parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2503",      key: "レグスペ",             parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: "角", },
      {wars_code: "2600",      key: "三間飛車",             parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2601",      key: "石田流",               parent: "三間飛車",         other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2602",      key: "早石田",               parent: "三間飛車",         other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2603",      key: "升田式石田流",         parent: "早石田",           other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      # 8
      {wars_code: "2604",      key: "鬼殺し",               parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: 3,   order_key: :sente, not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2605",      key: "△３ニ飛戦法",         parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: 2,   order_key: :gote,  not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2606",      key: "中田功XP",             parent: "三間飛車",         other_parents: nil, alias_names: "コーヤン流",                 turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2607",      key: "真部流",               parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2608",      key: "▲７八飛戦法",         parent: nil,                other_parents: nil, alias_names: "猫だまし戦法",               turn_limit: nil,  turn_eq: 1,   order_key: :sente, not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2609",      key: "４→３戦法",           parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2611",      key: "楠本式石田流",         parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2612",      key: "新石田流",             parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: 7,   order_key: :sente, not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2613",      key: "新鬼殺し",             parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: 7,   order_key: :sente, not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      # 9
      {wars_code: "2700",      key: "ダイレクト向かい飛車", parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: "角", },
      {wars_code: "2701",      key: "向かい飛車",           parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2702",      key: "メリケン向かい飛車",   parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2703",      key: "阪田流向飛車",         parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: "角", },
      {wars_code: "2704",      key: "角頭歩戦法",           parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: 4,    turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2705",      key: "鬼殺し向かい飛車",     parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: "角", },
      {wars_code: "2800",      key: "陽動振り飛車",         parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2801",      key: "玉頭銀",               parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: true, cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2802",      key: "つくつくぼうし戦法",   parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      # 10
      {wars_code: "2803",      key: "ひねり飛車",           parent: nil,                other_parents: nil, alias_names: ["縦歩取り", "児玉屋組"],     turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: true, cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2804",      key: "相振り飛車",           parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2806",      key: "角交換振り飛車",       parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: true, direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2807",      key: "きｍきｍ金",           parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2900",      key: "ポンポン桂",           parent: nil,                other_parents: nil, alias_names: "富沢キック",                 turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2901",      key: "５筋位取り",           parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2902",      key: "玉頭位取り",           parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2903",      key: "地下鉄飛車",           parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2904",      key: "飯島流引き角戦法",     parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      # 11
      {wars_code: "2905",      key: "丸山ワクチン",         parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: 10,   turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: true, direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: "角", },
      {wars_code:    nil,      key: "新丸山ワクチン",       parent: "丸山ワクチン",     other_parents: nil, alias_names: nil,                          turn_limit: 12,   turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: "角", },
      # {wars_code:    nil,      key: "佐藤新手▲9六歩",       parent: "丸山ワクチン",     other_parents: nil, alias_names: nil,                          turn_limit: 12,   turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: "角", },
      {wars_code: "2906",      key: "４六銀左急戦",         parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2907",      key: "４五歩早仕掛け",       parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2908",      key: "鷺宮定跡",             parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2909",      key: "棒銀",                 parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2910",      key: "４六銀右急戦",         parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2911",      key: "左美濃急戦",           parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2912",      key: "右四間飛車急戦",       parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2913",      key: "鳥刺し",               parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: nil,         key: "嬉野流",               parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: 2,    turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      # 12
      {wars_code: "2914",      key: "棒金",                 parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2915",      key: "超速",                 parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: 17,   turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2916",      key: "対振り持久戦",         parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2917",      key: "高田流左玉",           parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2918",      key: "７二飛亜急戦",         parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2919",      key: "袖飛車",               parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: "2920",      key: "一直線穴熊",           parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: true, cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      # その他
      {wars_code: nil,         key: "穴角戦法",             parent: nil,                other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: nil,         key: "穴角向かい飛車",       parent: "穴角戦法",         other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
      {wars_code: nil,         key: "うっかり三間飛車",     parent: nil,                other_parents: nil, alias_names: "菅井流三間飛車",             turn_limit: nil,  turn_eq: 6,   order_key: nil,    not_have_pawn: nil,  kill_only: nil,  direct_only: nil,  not_have_anything_except_pawn: nil,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_empty: nil, hold_piece_eq: nil,  },
    ]

    include PresetInfo::DelegateToShapeInfoMethods
    include DefenseInfo::AttackInfoSharedMethods

    def tactic_key
      :attack
    end

    def siratama_url
    end
  end
end
