# frozen-string-literal: true

module Bushido
  class AttackInfo
    include ApplicationMemoryRecord
    memory_record [
      # 1
      {wars_code: "2000", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-139.html",                  key: "３七銀戦法",           parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :sente, not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E7%9F%A2%E5%80%893%E4%B8%83%E9%8A%80",                                                                                        },
      {wars_code: "2001", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-159.html",                  key: "脇システム",           parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :sente, not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E8%84%87%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0",                                                                                },
      {wars_code: "2002", sankou_url: "http://mudasure.com/blog-entry-50.html",                                key: "矢倉棒銀",             parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E6%A3%92%E9%8A%80#%E7%9F%A2%E5%80%89%E6%A3%92%E9%8A%80",                                                                      },
      {wars_code: "2003", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-150.html",                  key: "森下システム",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :sente, not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E6%A3%AE%E4%B8%8B%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0",                                                                       },
      {wars_code: "2004", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-149.html",                  key: "雀刺し",               parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E9%9B%80%E5%88%BA%E3%81%97",                                                                                                  },
      {wars_code: "2005", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-147.html",                  key: "米長流急戦矢倉",       parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E7%B1%B3%E9%95%B7%E6%B5%81%E6%80%A5%E6%88%A6%E7%9F%A2%E5%80%89",                                                              },
      {wars_code: "2006", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-134.html",                  key: "カニカニ銀",           parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E3%82%AB%E3%83%8B%E3%82%AB%E3%83%8B%E9%8A%80",                                                                                },
      {wars_code: "2007", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-148.html",                  key: "中原流急戦矢倉",       parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E9%98%BF%E4%B9%85%E6%B4%A5%E6%B5%81%E6%80%A5%E6%88%A6%E7%9F%A2%E5%80%89",                                                     },
      {wars_code: "2008", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-146.html",                  key: "阿久津流急戦矢倉",     parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E9%98%BF%E4%B9%85%E6%B4%A5%E6%B5%81%E6%80%A5%E6%88%A6%E7%9F%A2%E5%80%89",                                                     },
      # 2
      {wars_code: "2009", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-152.html",                  key: "矢倉中飛車",           parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E7%9F%A2%E5%80%89%E4%B8%AD%E9%A3%9B%E8%BB%8A",                                                                                },
      {wars_code: "2010", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-129.html",                  key: "右四間飛車",           parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E5%8F%B3%E5%9B%9B%E9%96%93%E9%A3%9B%E8%BB%8A",                                                                                },
      {wars_code: "2011", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-137.html",                  key: "原始棒銀",             parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: true, kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E6%A3%92%E9%8A%80#.E5.8E.9F.E5.A7.8B.E6.A3.92.E9.8A.80",                                                                      },
      {wars_code: "2012", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-154.html",                  key: "右玉",                 parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E5%8F%B3%E7%8E%89",                                                                                                           },
      {wars_code: "2013", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-165.html",                  key: "かまいたち戦法",       parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E3%81%8B%E3%81%BE%E3%81%84%E3%81%9F%E3%81%A1%E6%88%A6%E6%B3%95",                                                              },
      {wars_code: "2014", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-125.html",                  key: "パックマン戦法",       parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: 2,   order_key: :gote,  not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/4%E5%9B%9B%E6%AD%A9%E3%83%91%E3%83%83%E3%82%AF%E3%83%9E%E3%83%B3",                                                             },
      {wars_code: "2015", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-153.html",                  key: "新米長玉",             parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: 2,   order_key: :gote,  not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E7%B1%B3%E9%95%B7%E7%8E%89#%E6%96%B0%E7%B1%B3%E9%95%B7%E7%8E%89",                                                             },
      {wars_code: "2016", sankou_url: "http://mudasure.com/blog-entry-64.html",                                key: "稲庭戦法",             parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: nil,                                           },
      {wars_code: "2017", sankou_url: "http://mudasure.com/blog-entry-65.html",                                key: "四手角",               parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: true,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E5%9B%9B%E6%89%8B%E8%A7%92",                                                                                                  },
      # 3
      {wars_code: "2019", sankou_url: nil,                                                                     key: "一間飛車",             parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: true,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E4%B8%80%E9%96%93%E9%A3%9B%E8%BB%8A",                                                                                                  },
      {wars_code: "2020", sankou_url: nil,                                                                     key: "一間飛車穴熊",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: true,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: nil,                                                                                                  },
      {wars_code: "2021", sankou_url: "http://syogikagaku.tokyo/162",                                          key: "都成流",               parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :gote,     not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: "歩",    wikipedia_url: nil,                                                                                                  },
      {wars_code: "2022", sankou_url: nil,                                                                     key: "右四間飛車左美濃",     parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: true,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: nil,                                                                                                  },
      {wars_code: "2100", sankou_url: "http://mudasure.com/blog-entry-66.html",                                key: "角換わり",             parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :sente, not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: "角",   wikipedia_url: "https://ja.wikipedia.org/wiki/%E8%A7%92%E6%8F%9B%E3%82%8F%E3%82%8A",                                                                                         },
      {wars_code: "2101", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-184.html",                  key: "角換わり腰掛け銀",     parent: "角換わり", other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: "角",   wikipedia_url: "https://ja.wikipedia.org/wiki/%E8%85%B0%E6%8E%9B%E3%81%91%E9%8A%80#%E8%A7%92%E6%8F%9B%E3%82%8F%E3%82%8A%E8%85%B0%E6%8E%9B%E3%81%91%E9%8A%80",                },
      {wars_code: "2102", sankou_url: nil,                                                                     key: "角換わり棒銀",         parent: "角換わり", other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: "角",   wikipedia_url: nil,                },
      {wars_code: "2103", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-182.html",                  key: "角換わり早繰り銀",     parent: "角換わり", other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: "角",   wikipedia_url: "https://ja.wikipedia.org/wiki/%E6%97%A9%E7%B9%B0%E3%82%8A%E9%8A%80#%E8%A7%92%E6%8F%9B%E3%82%8F%E3%82%8A",                                                    },
      {wars_code: "2104", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-126.html",                  key: "筋違い角",             parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: true, not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: 0,   hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E7%AD%8B%E9%81%95%E3%81%84%E8%A7%92",                                                                                         },
      # 4
      {wars_code: "2105", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-157.html",                  key: "木村定跡",             parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: "角",   wikipedia_url: "https://ja.wikipedia.org/wiki/%E6%9C%A8%E6%9D%91%E5%AE%9A%E8%B7%A1",                                                                                         },
      {wars_code: "2106", sankou_url: "http://mudasure.com/blog-entry-72.html",                                key: "一手損角換わり",       parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :gote,  not_have_pawn: nil,  kill_only: true, stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: "角",   wikipedia_url: "https://ja.wikipedia.org/wiki/%E5%BE%8C%E6%89%8B%E7%95%AA%E4%B8%80%E6%89%8B%E6%90%8D%E8%A7%92%E6%8F%9B%E3%82%8F%E3%82%8A",                                   },
      {wars_code: "2200", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-189.html",                  key: "相掛かり",             parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: 15,   turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: "歩",   wikipedia_url: "https://ja.wikipedia.org/wiki/%E7%9B%B8%E6%8E%9B%E3%81%8B%E3%82%8A",                                                                                         },
      {wars_code: "2201", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-191.html",                  key: "相掛かり棒銀",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: "歩",   wikipedia_url: "https://ja.wikipedia.org/wiki/%E6%A3%92%E9%8A%80#.E7.9B.B8.E6.8E.9B.E3.81.8B.E3.82.8A.E6.A3.92.E9.8A.80",                                                    },
      {wars_code: "2202", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-194.html",                  key: "塚田スペシャル",       parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: true, not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E5%A1%9A%E7%94%B0%E3%82%B9%E3%83%9A%E3%82%B7%E3%83%A3%E3%83%AB",                                                              },
      {wars_code: "2203", sankou_url: "http://mudasure.com/blog-entry-76.html",                                key: "中原流相掛かり",       parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E7%9B%B8%E6%8E%9B%E3%81%8B%E3%82%8A#%E7%9B%B8%E6%8E%9B%E3%81%8B%E3%82%8A%E3%81%AE%E8%AB%B8%E6%88%A6%E6%B3%95",                },
      {wars_code: "2204", sankou_url: "http://mudasure.com/blog-entry-77.html",                                key: "中原飛車",             parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E7%9B%B8%E6%8E%9B%E3%81%8B%E3%82%8A#%E7%9B%B8%E6%8E%9B%E3%81%8B%E3%82%8A%E3%81%AE%E8%AB%B8%E6%88%A6%E6%B3%95",                },
      {wars_code: "2205", sankou_url: "http://mudasure.com/blog-entry-78.html",                                key: "腰掛け銀",             parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: "角", hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E8%85%B0%E6%8E%9B%E3%81%91%E9%8A%80",                                                                                         }, # ノーマル腰掛け銀
      {wars_code: "2206", sankou_url: "http://mudasure.com/blog-entry-79.html",                                key: "鎖鎌銀",               parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: "角", hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E7%9B%B8%E6%8E%9B%E3%81%8B%E3%82%8A#%E7%9B%B8%E6%8E%9B%E3%81%8B%E3%82%8A%E3%81%AE%E8%AB%B8%E6%88%A6%E6%B3%95",                },
      # 5
      {wars_code: "2207", sankou_url: "http://mudasure.com/blog-entry-80.html",                                key: "８五飛車戦法",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,    cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E6%A8%AA%E6%AD%A9%E5%8F%96%E3%82%8A8%E4%BA%94%E9%A3%9B",                                                                      },
      {wars_code: "2208", sankou_url: nil,                                                                     key: "UFO銀",                parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: true,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: nil,                                                                      },
      {wars_code: "2300", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-198.html",                  key: "横歩取り",             parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E6%A8%AA%E6%AD%A9%E5%8F%96%E3%82%8A",                                                                                         },
      {wars_code: "2301", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-199.html",                  key: "△３三角型空中戦法",   parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :gote,     not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E6%A8%AA%E6%AD%A9%E5%8F%96%E3%82%8A3%E4%B8%89%E8%A7%92",                                                                      },
      {wars_code: "2302", sankou_url: "http://mudasure.com/blog-entry-84.html",                                key: "△３三桂戦法",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :gote,     not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E6%A8%AA%E6%AD%A9%E5%8F%96%E3%82%8A3%E4%B8%89%E6%A1%82",                                                                      },
      {wars_code: "2303", sankou_url: "http://mudasure.com/blog-entry-85.html",                                key: "△２三歩戦法",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :gote,     not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E6%A8%AA%E6%AD%A9%E5%8F%96%E3%82%8A2%E4%B8%89%E6%AD%A9",                                                                      },
      {wars_code: "2304", sankou_url: "http://mudasure.com/blog-entry-86.html",                                key: "△４五角戦法",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: :gote,  not_have_pawn: nil,  kill_only: nil,  stroke_only: true, not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E6%A8%AA%E6%AD%A9%E5%8F%96%E3%82%8A4%E4%BA%94%E8%A7%92",                                                                      },
      {wars_code: "2305", sankou_url: "http://mudasure.com/blog-entry-87.html",                                key: "相横歩取り",           parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: "角", hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E7%9B%B8%E6%A8%AA%E6%AD%A9%E5%8F%96%E3%82%8A",                                                                                },
      {wars_code: "2400", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-151.html",                  key: "ゴキゲン中飛車",       parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E3%82%B4%E3%82%AD%E3%82%B2%E3%83%B3%E4%B8%AD%E9%A3%9B%E8%BB%8A",                                                              },
      # 6
      {wars_code: "2401", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-133.html",                  key: "ツノ銀中飛車",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E3%83%84%E3%83%8E%E9%8A%80%E4%B8%AD%E9%A3%9B%E8%BB%8A",                                                                       },
      {wars_code: "2402", sankou_url: "http://mudasure.com/blog-entry-90.html",                                key: "平目",                 parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E5%B9%B3%E7%9B%AE_(%E5%B0%86%E6%A3%8B)",                                                                                      },
      {wars_code: "2403", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-155.html",                  key: "風車",                 parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E9%A2%A8%E8%BB%8A",                                                                                                           },
      {wars_code: nil,    sankou_url: nil,                                                                     key: "新風車",               parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E9%A2%A8%E8%BB%8A_(%E5%B0%86%E6%A3%8B)",                                                                                      },
      {wars_code: "2404", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-130.html",                  key: "英ちゃん流中飛車",     parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E4%B8%AD%E9%A3%9B%E8%BB%8A",                                                                                                  },
      {wars_code: "2405", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-140.html",                  key: "原始中飛車",           parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E5%8E%9F%E5%A7%8B%E4%B8%AD%E9%A3%9B%E8%BB%8A",                                                                                },
      {wars_code: "2406", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-161.html",                  key: "加藤流袖飛車",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E8%A2%96%E9%A3%9B%E8%BB%8A",                                                                                                  },
      {wars_code: "2407", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-162.html",                  key: "５七金戦法",           parent: nil,        other_parents: nil, alias_names: ["４六金戦法", "金立ち戦法"], turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/4%E5%85%AD%E9%87%91%E6%88%A6%E6%B3%95",                                                                        },
      {wars_code: "2408", sankou_url: "http://mudasure.com/blog-entry-96.html",                                key: "超急戦",               parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/4%E4%BA%94%E6%AD%A9%E6%97%A9%E4%BB%95%E6%8E%9B%E3%81%91#.E8.B6.85.E6.80.A5.E6.88.A6",                                          },
      {wars_code: "2410", sankou_url: nil,                                                                     key: "中飛車左穴熊",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: nil,                                          },
      # 7
      {wars_code: "2411", sankou_url: nil,                                                                     key: "遠山流",               parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: "角",  hold_piece_count_eq: nil, hold_piece_eq: nil,   wikipedia_url: nil,                                          },
      {wars_code: "2500", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-127.html",                  key: "四間飛車",             parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E5%9B%9B%E9%96%93%E9%A3%9B%E8%BB%8A",                                                                                         },
      {wars_code: "2501", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-128.html",                  key: "藤井システム",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E8%97%A4%E4%BA%95%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0",                                                                       },
      {wars_code: "2502", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-131.html",                  key: "立石流",               parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E7%AB%8B%E7%9F%B3%E6%B5%81%E5%9B%9B%E9%96%93%E9%A3%9B%E8%BB%8A",                                                              },
      {wars_code: "2503", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-132.html",                  key: "レグスペ",             parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: "角",   wikipedia_url: "https://ja.wikipedia.org/wiki/%E5%9B%9B%E9%96%93%E9%A3%9B%E8%BB%8A#%E5%9B%9B%E9%96%93%E9%A3%9B%E8%BB%8A%E3%81%AE%E7%A8%AE%E5%88%A5",                         },
      {wars_code: "2600", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-141.html",                  key: "三間飛車",             parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E4%B8%89%E9%96%93%E9%A3%9B%E8%BB%8A",                                                                                         },
      {wars_code: "2601", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-145.html",                  key: "石田流",               parent: "三間飛車", other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E7%9F%B3%E7%94%B0%E6%B5%81",                                                                                                  },
      {wars_code: "2602", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-144.html",                  key: "早石田",               parent: "三間飛車", other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E7%9F%B3%E7%94%B0%E6%B5%81#%E6%97%A9%E7%9F%B3%E7%94%B0",                                                                      },
      {wars_code: "2603", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-143.html",                  key: "升田式石田流",         parent: "早石田",   other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E7%9F%B3%E7%94%B0%E6%B5%81#.E5.8D.87.E7.94.B0.E5.BC.8F.E7.9F.B3.E7.94.B0.E6.B5.81",                                           },
      # 8
      {wars_code: "2604", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-188.html",                  key: "鬼殺し",               parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: 3,   order_key: :sente, not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E9%AC%BC%E6%AE%BA%E3%81%97_(%E5%B0%86%E6%A3%8B)",                                                                             },
      {wars_code: "2605", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-142.html",                  key: "△３ニ飛戦法",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: 2,   order_key: :gote,  not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/2%E6%89%8B%E7%9B%AE%E2%96%B33%E4%BA%8C%E9%A3%9B",                                                                              },
      {wars_code: "2606", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-163.html",                  key: "中田功ＸＰ",           parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E4%B8%AD%E7%94%B0%E5%8A%9FXP",                                                                                                },
      {wars_code: "2607", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-164.html",                  key: "真部流",               parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E4%B8%89%E9%96%93%E9%A3%9B%E8%BB%8A#%E6%88%A6%E6%B3%95",                                                                      },
      {wars_code: "2608", sankou_url: "http://mudasure.com/blog-entry-110.html",                               key: "▲７八飛戦法",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: 1,   order_key: :sente, not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E4%B8%89%E9%96%93%E9%A3%9B%E8%BB%8A#%E6%88%A6%E6%B3%95",                                                                      },
      {wars_code: "2609", sankou_url: "http://mudasure.com/blog-entry-111.html",                               key: "４→３戦法",           parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E4%B8%89%E9%96%93%E9%A3%9B%E8%BB%8A#%E6%88%A6%E6%B3%95",                                                                      },
      {wars_code: "2611", sankou_url: "http://mudasure.com/blog-entry-112.html",                               key: "楠本式石田流",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E4%B8%89%E9%96%93%E9%A3%9B%E8%BB%8A#%E6%88%A6%E6%B3%95",                                                                      },
      {wars_code: "2612", sankou_url: "http://mudasure.com/blog-entry-113.html",                               key: "新石田流",             parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: 7,   order_key: :sente, not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E7%9F%B3%E7%94%B0%E6%B5%81#.E6.96.B0.E3.83.BB.E7.9F.B3.E7.94.B0.E6.B5.81",                                                    },
      {wars_code: "2613", sankou_url: "http://mudasure.com/blog-entry-114.html",                               key: "新鬼殺し",             parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: 7,   order_key: :sente, not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E9%AC%BC%E6%AE%BA%E3%81%97_(%E5%B0%86%E6%A3%8B)#.E6.96.B0.E3.83.BB.E9.AC.BC.E6.AE.BA.E3.81.97",                               }, # OK
      # 9
      {wars_code: "2700", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-174.html",                  key: "ダイレクト向かい飛車", parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: "角",   wikipedia_url: "https://ja.wikipedia.org/wiki/%E3%83%80%E3%82%A4%E3%83%AC%E3%82%AF%E3%83%88%E5%90%91%E3%81%8B%E3%81%84%E9%A3%9B%E8%BB%8A",                                   },
      {wars_code: "2701", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-135.html",                  key: "向かい飛車",           parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E5%90%91%E3%81%8B%E3%81%84%E9%A3%9B%E8%BB%8A",                                                                                },
      {wars_code: "2702", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-136.html",                  key: "メリケン向かい飛車",   parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E5%90%91%E3%81%8B%E3%81%84%E9%A3%9B%E8%BB%8A#%E5%90%91%E3%81%8B%E3%81%84%E9%A3%9B%E8%BB%8A%E3%81%AE%E7%A8%AE%E5%88%A5",       },
      {wars_code: "2703", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-176.html",                  key: "阪田流向飛車",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: "角",   wikipedia_url: "https://ja.wikipedia.org/wiki/%E9%98%AA%E7%94%B0%E6%B5%81%E5%90%91%E3%81%8B%E3%81%84%E9%A3%9B%E8%BB%8A",                                                     },
      {wars_code: "2704", sankou_url: "http://mudasure.com/blog-entry-119.html",                               key: "角頭歩戦法",           parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: 4,    turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E8%A7%92%E9%A0%AD%E6%AD%A9%E6%88%A6%E6%B3%95",                                                                                },
      {wars_code: "2705", sankou_url: "http://mudasure.com/blog-entry-120.html",                               key: "鬼殺し向かい飛車",     parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: "角",   wikipedia_url: "https://ja.wikipedia.org/wiki/%E9%AC%BC%E6%AE%BA%E3%81%97_(%E5%B0%86%E6%A3%8B)#.E9.AC.BC.E6.AE.BA.E3.81.97.E5.90.91.E3.81.8B.E3.81.84.E9.A3.9B.E8.BB.8A",    },
      {wars_code: "2800", sankou_url: "https://www.youtube.com/watch?v=kEfgOQoMqsM",                           key: "陽動振り飛車",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E9%99%BD%E5%8B%95%E6%8C%AF%E3%82%8A%E9%A3%9B%E8%BB%8A",                                                                       },
      {wars_code: "2801", sankou_url: nil,                                                                     key: "玉頭銀",               parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: true,  cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E7%8E%89%E9%A0%AD%E9%8A%80", },
      {wars_code: "2802", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-186.html",                  key: "つくつくぼうし戦法",   parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://www.google.co.jp/search?source=ig&hl=ja&lr=lang_ja&q=%E3%81%A4%E3%81%8F%E3%81%A4%E3%81%8F%E3%81%BC%E3%81%86%E3%81%97%E6%88%A6%E6%B3%95%20wikipedia", },
      # 10
      {wars_code: "2803", sankou_url: nil,                                                                     key: "ひねり飛車",           parent: nil,        other_parents: nil, alias_names: ["縦歩取り", "児玉屋組"],     turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,   not_have_anything_except_pawn: true,  cold_war: nil, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E3%81%B2%E3%81%AD%E3%82%8A%E9%A3%9B%E8%BB%8A",                },
      {wars_code: "2804", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-190.html",                  key: "相振り飛車",           parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,   not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E5%B0%86%E6%A3%8B%E3%81%AE%E6%88%A6%E6%B3%95%E4%B8%80%E8%A6%A7#.E7.9B.B8.E6.8C.AF.E3.82.8A.E9.A3.9B.E8.BB.8A",                },
      {wars_code: "2806", sankou_url: nil,                                                                     key: "角交換振り飛車",       parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: true,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E8%A7%92%E4%BA%A4%E6%8F%9B%E6%8C%AF%E3%82%8A%E9%A3%9B%E8%BB%8A",                },
      {wars_code: "2807", sankou_url: nil,                                                                     key: "きｍきｍ金",           parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: nil,                },
      {wars_code: "2900", sankou_url: "https://youtu.be/ghj92TX1FD0",                                          key: "ポンポン桂",           parent: nil,        other_parents: nil, alias_names: "富沢キック",                 turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E3%83%9D%E3%83%B3%E3%83%9D%E3%83%B3%E6%A1%82",                                                                                },
      {wars_code: "2901", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-168.html",                  key: "５筋位取り",           parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/5%E7%AD%8B%E4%BD%8D%E5%8F%96%E3%82%8A",                                                                                        },
      {wars_code: "2902", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-167.html",                  key: "玉頭位取り",           parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E7%8E%89%E9%A0%AD%E4%BD%8D%E5%8F%96%E3%82%8A",                                                                                },
      {wars_code: "2903", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-156.html",                  key: "地下鉄飛車",           parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E5%9C%B0%E4%B8%8B%E9%89%84%E9%A3%9B%E8%BB%8A",                                                                                },
      {wars_code: "2904", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-170.html",                  key: "飯島流引き角戦法",     parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E9%A3%AF%E5%B3%B6%E6%A0%84%E6%B2%BB#%E9%A3%AF%E5%B3%B6%E6%B5%81%E5%BC%95%E3%81%8D%E8%A7%92%E6%88%A6%E6%B3%95",                },
      # 11
      {wars_code: "2905", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-183.html",                  key: "丸山ワクチン",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: 10,   turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: true, stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: "角",   wikipedia_url: "https://ja.wikipedia.org/wiki/%E3%82%B4%E3%82%AD%E3%82%B2%E3%83%B3%E4%B8%AD%E9%A3%9B%E8%BB%8A#.E4.B8.B8.E5.B1.B1.E3.83.AF.E3.82.AF.E3.83.81.E3.83.B3",       },
      {wars_code: "2906", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-175.html",                  key: "４六銀左急戦",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/4%E5%85%AD%E9%8A%80%E5%B7%A6%E6%88%A6%E6%B3%95",                                                                               },
      {wars_code: "2907", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-171.html",                  key: "４五歩早仕掛け",       parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/4%E4%BA%94%E6%AD%A9%E6%97%A9%E4%BB%95%E6%8E%9B%E3%81%91",                                                                      },
      {wars_code: "2908", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-173.html",                  key: "鷺宮定跡",             parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E9%B7%BA%E5%AE%AE%E5%AE%9A%E8%B7%A1",                                                                                         },
      {wars_code: "2909", sankou_url: "",                                                                      key: "棒銀",                 parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E6%A3%92%E9%8A%80",                                                                                         },
      {wars_code: "2910", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-177.html",                  key: "４六銀右急戦",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/4%E5%85%AD%E9%8A%80%E5%8F%B3%E6%88%A6%E6%B3%95",                                                                               },
      {wars_code: "2911", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-178.html",                  key: "左美濃急戦",           parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://www.google.co.jp/search?source=ig&hl=ja&lr=lang_ja&q=%E5%B7%A6%E7%BE%8E%E6%BF%83%E6%80%A5%E6%88%A6%20wikipedia",                                     },
      {wars_code: "2912", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-179.html",                  key: "右四間飛車急戦",       parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E5%8F%B3%E5%9B%9B%E9%96%93%E9%A3%9B%E8%BB%8A#.E6.88.A6.E6.B3.95",                                                             },
      {wars_code: "2913", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-166.html",                  key: "鳥刺し",               parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E5%AC%89%E9%87%8E%E6%B5%81#%E9%96%A2%E9%80%A3%E3%81%99%E3%82%8B%E6%88%A6%E6%B3%95",                                           },
      {wars_code: nil,    sankou_url: nil,                                                                     key: "嬉野流",               parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: 2,    turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E5%AC%89%E9%87%8E%E6%B5%81",                                                                                                  },
      # 12
      {wars_code: "2914", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-138.html",                  key: "棒金",                 parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,   hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E6%A3%92%E9%87%91",                                                                                                           },
      {wars_code: "2915", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-187.html",                  key: "超速",                 parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: 17,   turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,   hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E3%82%B4%E3%82%AD%E3%82%B2%E3%83%B3%E4%B8%AD%E9%A3%9B%E8%BB%8A#.E8.B6.85.E9.80.9F.E2.96.B23.E4.B8.83.E9.8A.80",              },
      {wars_code: "2916", sankou_url: "https://www.youtube.com/watch?v=uNo4Wm7Ga5s",                           key: "対振り持久戦",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: nil,              },

      {wars_code: "2917", sankou_url: nil,                                                                     key: "高田流左玉",           parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: nil,              },
      {wars_code: "2918", sankou_url: "https://www.youtube.com/watch?v=76nChig4kkc",                           key: "７二飛亜急戦",         parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: nil,              },
      {wars_code: "2919", sankou_url: nil,                                                                     key: "袖飛車",               parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: "https://ja.wikipedia.org/wiki/%E8%A2%96%E9%A3%9B%E8%BB%8A",              },
      {wars_code: "2920", sankou_url: nil,                                                                     key: "一直線穴熊",           parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: nil,  hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: nil,              },

      # その他
      {wars_code: nil,    sankou_url: nil,                                                                     key: "穴角戦法",             parent: nil,        other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: nil,                                                                                                  },
      {wars_code: nil,    sankou_url: nil,                                                                     key: "穴角向かい飛車",       parent: "穴角戦法", other_parents: nil, alias_names: nil,                          turn_limit: nil,  turn_eq: nil, order_key: nil,       not_have_pawn: nil,  kill_only: nil,  stroke_only: nil,  not_have_anything_except_pawn: nil,   cold_war: true, hold_piece_not_in: nil,  hold_piece_in: nil,  hold_piece_count_eq: nil, hold_piece_eq: nil,    wikipedia_url: nil,                                                                                                  },
    ]

    include TeaiwariInfo::DelegateToShapeInfoMethods
    include DefenseInfo::AttackInfoSharedMethods

    def tactic_key
      :attack
    end

    def siratama_url
    end
  end
end
