# frozen-string-literal: true

module Bushido
  class DefenseInfo
    include ApplicationMemoryRecord
    memory_record [
      {wars_code: "000",  key: "カニ囲い",         evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "居飛車",   defense_group_info: "矢倉変化系",         sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-88.html",  siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/ibisya/kanigakoi.html",            },
      {wars_code: "001",  key: "金矢倉",           evolution_keys: ["総矢倉", "菱矢倉"],       turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: "矢倉囲い", sect_key: "居飛車",   defense_group_info: "基本的な囲い",       sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-89.html",  siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/ibisya/kinyagura.html",            },
      {wars_code: "002",  key: "銀矢倉",           evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "居飛車",   defense_group_info: "矢倉変化系",         sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-90.html",  siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/ibisya/ginyagura.html",            },
      {wars_code: "003",  key: "片矢倉",           evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: "天野矢倉", sect_key: "居飛車",   defense_group_info: "矢倉変化系",         sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-91.html",  siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/ibisya/katayagura.html",           },
      {wars_code: "004",  key: "総矢倉",           evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "居飛車",   defense_group_info: "矢倉変化系",         sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-92.html",  siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/ibisya/souyagura.html",            },
      {wars_code: "005",  key: "矢倉穴熊",         evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "居飛車",   defense_group_info: "矢倉変化系",         sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-93.html",  siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/ibisya/yaguraanaguma.html",        },
      {wars_code: "006",  key: "菊水穴熊",         evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "居飛車",   defense_group_info: "矢倉変化系",         sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-94.html",  siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/ibisya/kikusuiyagura.html",        },
      {wars_code: "007",  key: "銀立ち矢倉",       evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "居飛車",   defense_group_info: "矢倉変化系",         sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-95.html",  siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/ibisya/gindatiyagura.html",        },
      {wars_code: "008",  key: "菱矢倉",           evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "居飛車",   defense_group_info: "矢倉変化系",         sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-96.html",  siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/ibisya/hisiyagura.html",           },
      {wars_code: "009",  key: "雁木囲い",         evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "居飛車",   defense_group_info: "その他の囲い",       sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-97.html",  siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/ibisya/ganngi.html",               },
      {wars_code: "010",  key: "ボナンザ囲い",     evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "居飛車",   defense_group_info: "その他の囲い",       sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-98.html",  siratama_url: nil,                                                                                     },
      {wars_code: "100",  key: "美濃囲い",         evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "居飛車",   defense_group_info: "美濃囲い変化形",     sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-99.html",  siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/furibisya/minokakoi.html",         },
      {wars_code: "101",  key: "高美濃囲い",       evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "振り飛車", defense_group_info: "美濃囲い変化形",     sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-99.html",  siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/furibisya/takaminokakoi.html",     },
      {wars_code: "102",  key: "銀冠",             evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "振り飛車", defense_group_info: "美濃囲い変化形",     sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-101.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/furibisya/ginkannmuri.html",       },
      {wars_code: "103",  key: "銀美濃",           evolution_keys: ["ダイヤモンド美濃"],       turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "振り飛車", defense_group_info: "美濃囲い変化形",     sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-102.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/furibisya/ginmino.html",           },
      {wars_code: "104",  key: "ダイヤモンド美濃", evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "振り飛車", defense_group_info: "美濃囲い変化形",     sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-103.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/furibisya/daiyamondomino.html",    },
      {wars_code: "105",  key: "木村美濃",         evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "振り飛車", defense_group_info: "美濃囲い変化形",     sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-104.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/furibisya/kimuramino.html",        },
      {wars_code: "106",  key: "片美濃囲い",       evolution_keys: ["美濃囲い", "高美濃囲い"], turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "振り飛車", defense_group_info: "美濃囲い変化形",     sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-105.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/furibisya/kataminokakoi.html",     },
      {wars_code: "107",  key: "ちょんまげ美濃",   evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "振り飛車", defense_group_info: "美濃囲い変化形",     sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-106.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/furibisya/tyonmagemino.html",      },
      {wars_code: "108",  key: "坊主美濃",         evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "振り飛車", defense_group_info: "美濃囲い変化形",     sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-107.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/furibisya/tyonmagemino.html",      },
      {wars_code: "200",  key: "左美濃",           evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "振り飛車", defense_group_info: "美濃囲い変化形",     sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-108.html", siratama_url: nil,                                                                                     },
      {wars_code: "201",  key: "天守閣美濃",       evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "居飛車",   defense_group_info: "美濃囲い変化形",     sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-109.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/ibisya/tennsyukakumino.html",      },
      {wars_code: "202",  key: "四枚美濃",         evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "振り飛車", defense_group_info: "美濃囲い変化形",     sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-110.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/furibisya/yonmaimino.html",        },
      {wars_code: "203",  key: "端玉銀冠",         evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "居飛車",   defense_group_info: "美濃囲い変化形",     sankou_url: "http://mudasure.com/blog-entry-26.html",               siratama_url: nil, process_ki2: "▲２六歩 △３四歩 ▲７六歩 △４四歩 ▲４八銀 △４二飛 ▲６八玉 △６二玉 ▲７八玉 △７二銀 ▲５六歩 △７一玉 ▲５八金右 △３二銀 ▲５七銀 △５二金左 ▲９六歩 △９四歩 ▲８六歩 △６四歩 ▲８七玉 △７四歩 ▲７八銀 △７三桂 ▲９八玉 △４三銀 ▲２五歩 △３三角 ▲８七銀 △８四歩 ▲７八金" },
      {wars_code: "204",  key: "串カツ囲い",       evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "居飛車",   defense_group_info: "穴熊変化形",         sankou_url: "http://mudasure.com/blog-entry-27.html",               siratama_url: nil,        },
      {wars_code: "300",  key: "舟囲い",           evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "居飛車",   defense_group_info: "基本的な囲い",       sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-111.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/ibisya/funagakoi.html",            },
      {wars_code: "301",  key: "居飛車穴熊",       evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: "イビ穴",   sect_key: "居飛車",   defense_group_info: "基本的な囲い",       sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-112.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/ibisya/anaguma.html",              },
      {wars_code: "302",  key: "松尾流穴熊",       evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "振り飛車", defense_group_info: "穴熊変化形",         sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-113.html", siratama_url: nil,                                                                                     },
      {wars_code: "303",  key: "銀冠穴熊",         evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "振り飛車", defense_group_info: "穴熊変化形",         sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-114.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/furibisya/ginkanmurianaguma.html", },
      {wars_code: "304",  key: "ビッグ４",         evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "居飛車",   defense_group_info: "穴熊変化形",         sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-115.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/ibisya/big4.html",                 },
      {wars_code: "305",  key: "箱入り娘",         evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "居飛車",   defense_group_info: "穴熊変化形",         sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-116.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/ibisya/hakoirimusume.html",        },
      {wars_code: "306",  key: "ミレニアム囲い",   evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "振り飛車", defense_group_info: "穴熊変化形",         sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-117.html", siratama_url: nil,                                                                                     },
      {wars_code: "400",  key: "振り飛車穴熊",     evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "振り飛車", defense_group_info: "穴熊変化形",         sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-118.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/furibisya/anaguma.html",           },
      {wars_code: "401",  key: "右矢倉",           evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "振り飛車", defense_group_info: "矢倉変化系",         sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-119.html", siratama_url: nil,                                                                                     },
      {wars_code: "402",  key: "金無双",           evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "振り飛車", defense_group_info: "基本的な囲い",       sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-120.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/furibisya/kinmusou.html",          },
      {wars_code: "403",  key: "中住まい",         evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "居飛車",   defense_group_info: "自陣全体を守る囲い", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-121.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/ibisya/nakazumai.html",            },
      {wars_code: "404",  key: "中原玉",           evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "居飛車",   defense_group_info: "自陣全体を守る囲い", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-122.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/ibisya/nakaharagakoi.html",        },
      {wars_code: "500",  key: "アヒル囲い",       evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: "金開き",   sect_key: "居飛車",   defense_group_info: "自陣全体を守る囲い", sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-123.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/ibisya/kinnbiraki.html",           },
      {wars_code: "501",  key: "いちご囲い",       evolution_keys: nil,                        turn_limit: nil, turn_eq: nil, compare_my_side_only: true, compare_condition: :include, only_location_key: nil, fuganai: false, kaisenmae: false, mochigoma_eq: nil, triggers: nil,  alias_names: nil,        sect_key: "居飛車",   defense_group_info: "その他の囲い",       sankou_url: "http://mijinko83.blog110.fc2.com/blog-entry-124.html", siratama_url: "http://www5e.biglobe.ne.jp/~siratama/nonframe/syougi/ibisya/ichigogakoi.html",          },
    ]

    include TeaiwariInfo::DelegateToShapeInfoMethods

    concerning :AttackInfoSharedMethods do
      def alias_names
        Array(super)
      end

      def sect_info
        SectInfo.fetch(sect_key)
      end

      def evolution_keys
        Array(super)
      end

      def triggers
        Array(super).collect do |e|
          Soldier.from_str(e)
        end
      end

      def mochigoma_eq
        if super
          Utils.hold_pieces_s_to_a(super)
        end
      end

      def self_check
        if process_ki2
          info = Parser.parse(process_ki2)
          names = info.mediator.players.flat_map do |e|
            (e.defense_infos + e.attack_infos).collect(&:name)
          end
          if names.include?(name)
            names
          end
        end
      end
    end
  end
end
