source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "compass"      # for stylesheet.css
gem "sass"         # for stylesheet.css
gem "redis"        # でかいセッション保持用
gem "rack-contrib" # Rack::Runtime 等
gem "haml"         # for view
gem "hpricot"      # for html2haml
gem "builder"      # for active_support の to_xml ?
gem "multi_json"   # for sinatra/json ?

gem 'coffee-script'
gem 'execjs'

gem "slim"
gem "puma"

gem "foreman"

gem "warabi", path: "../"
