source "https://rubygems.org"

gem "bioshogi", path: ".."
gem "mechanize"
gem "test-unit"
gem "stackprof"
gem "faraday"
gem "diff-lcs"
gem "benchmark-ips"
gem "color", ">= 2.0.0"

# bioshogiをフルで使う場合に必要なもの
# これからは gemspec で必須にしていない
gem "rubyzip", "~> 2.3.0", require: "zip"
gem "rmagick"
gem "systemu"
gem "zeitwerk"
