require_relative "diver/base"
require_relative "diver/nega_max_diver"
require_relative "diver/nega_alpha_diver"
require_relative "diver/nega_alpha_mate_diver"
require_relative "diver/nega_scout_diver"
